/// The v1 engine: `dart compile js` + node_preamble.
///
/// dart2js output resolves its global scope as
/// `typeof self != "undefined" ? self : globalThis`; node_preamble defines
/// `self` for Node (as `Object.create(globalThis)`) and exposes the CommonJS
/// `exports` object on it. The generated facade installs the exports there,
/// which makes the compiled artifact a real `require()`-able CommonJS module
/// — no global-namespace handshake needed on the CJS path.
library;

import 'dart:io';

import 'package:node_preamble/preamble.dart' as node_preamble;
import 'package:path/path.dart' as p;

import '../diagnostics.dart';
import 'compiler_backend.dart';

final class Dart2JsBackend implements CompilerBackend {
  @override
  String get id => 'dart2js';

  @override
  Future<BackendOutput> build(BackendBuildRequest request) async {
    final workDir = p.dirname(request.facadePath);
    final compiledPath = p.join(workDir, 'out.dart.js');

    final dart = Platform.resolvedExecutable;
    final args = [
      'compile',
      'js',
      '-O2',
      '-o',
      compiledPath,
      request.facadePath,
    ];
    if (request.verbose) {
      stderr.writeln('[dart2js] ${[dart, ...args].join(' ')}');
    }
    final result = await Process.run(
      dart,
      args,
      workingDirectory: request.targetPackageRoot,
    );
    if (result.exitCode != 0) {
      throw BuildException(
        'dart compile js failed (exit ${result.exitCode}):\n'
        '${result.stdout}\n${result.stderr}',
      );
    }

    // Assemble the runtime artifact: Node preamble + compiled program, with
    // the source-map pointer stripped (the .map file is not shipped).
    final compiled = File(compiledPath).readAsStringSync().replaceAll(
      RegExp(r'^//# sourceMappingURL=.*$', multiLine: true),
      '',
    );
    // The compiled program is a CommonJS script. Inside an ESM package
    // ("type": "module") a `.js` extension would make Node treat it as an ES
    // module and `require()` of it fails — `.cjs` is unambiguous.
    final runtimeName = switch (request.moduleFormat) {
      ModuleFormat.commonjs => '${request.artifactBaseName}.dart.js',
      ModuleFormat.esm => '${request.artifactBaseName}.dart.cjs',
    };
    File(p.join(request.outputDir, runtimeName)).writeAsStringSync(
      '${node_preamble.getPreamble(minified: true)}\n$compiled',
    );

    final entryName = 'index.js';
    final entrySource = switch (request.moduleFormat) {
      ModuleFormat.commonjs => _commonjsEntry(request, runtimeName),
      ModuleFormat.esm => _esmEntry(request, runtimeName),
    };
    File(p.join(request.outputDir, entryName)).writeAsStringSync(entrySource);

    return BackendOutput(
      emittedFiles: [entryName, runtimeName],
      packageJsonFields: {
        'type': switch (request.moduleFormat) {
          ModuleFormat.commonjs => 'commonjs',
          ModuleFormat.esm => 'module',
        },
        'engines': {'node': '>=18'},
      },
    );
  }

  String _commonjsEntry(BackendBuildRequest request, String runtimeName) {
    final firestore = request.api.usesFirestoreTimestamp
        ? '// DateTime crosses as a Firestore Timestamp: inject the class for\n'
              '// the compiled Dart program (firebase-admin is a peer '
              'dependency).\n'
              'const { Timestamp: __dtb\$Timestamp } = '
              'require("firebase-admin/firestore");\n'
              'globalThis.__dtb_Timestamp__ = __dtb\$Timestamp;\n'
        : '';
    final names = request.api.exportedNames;
    return '''
"use strict";
// Generated by dart_typescript_builder — Node CommonJS entry (dart2js engine).
// The compiled Dart program installs its exports onto this module's exports
// via node_preamble.
// Boundary validation errors are thrown through this JS frame so they carry
// a readable message on every engine.
globalThis.__dtb_throw__ ??= (message) => {
  throw new TypeError(message);
};
${firestore}const __dtb\$exports = require("./$runtimeName");
module.exports = __dtb\$exports;
// Static named-export hints so Node's cjs-module-lexer lets ESM consumers
// use named imports of this CommonJS module.
${names.map((n) => 'module.exports.$n = __dtb\$exports.$n;').join('\n')}
''';
  }

  String _esmEntry(BackendBuildRequest request, String runtimeName) {
    final buffer = StringBuffer()
      ..writeln(
        '// Generated by dart_typescript_builder — Node ESM entry '
        '(dart2js engine).',
      )
      ..writeln('globalThis.__dtb_throw__ ??= (message) => {')
      ..writeln('  throw new TypeError(message);')
      ..writeln('};');
    // Glue locals use a `__dtb$` prefix: Dart cannot export names starting
    // with `_`, so exported names can never collide with them.
    if (request.api.usesFirestoreTimestamp) {
      buffer
        ..writeln(
          'import { Timestamp as __dtb\$Timestamp } from '
          '"firebase-admin/firestore";',
        )
        ..writeln('globalThis.__dtb_Timestamp__ = __dtb\$Timestamp;');
    }
    buffer
      ..writeln(
        'import { createRequire as __dtb\$createRequire } from "node:module";',
      )
      ..writeln(
        'const __dtb\$exports = __dtb\$createRequire(import.meta.url)'
        '("./$runtimeName");',
      )
      ..writeln();
    for (final name in request.api.exportedNames) {
      buffer.writeln('export const $name = __dtb\$exports.$name;');
    }
    buffer
      ..writeln()
      ..writeln('export default __dtb\$exports;');
    return buffer.toString();
  }
}
