/// The v1 engine: `dart compile js` + node_preamble.
///
/// dart2js output resolves its global scope as
/// `typeof self != "undefined" ? self : globalThis`; node_preamble defines
/// `self` for Node (as `Object.create(globalThis)`) and exposes the CommonJS
/// `exports` object on it. The generated facade installs the exports there,
/// which makes the compiled artifact a real `require()`-able CommonJS module
/// — no global-namespace handshake needed on the CJS path.
library;

import 'dart:io';

import 'package:node_preamble/preamble.dart' as node_preamble;
import 'package:path/path.dart' as p;

import '../diagnostics.dart';
import 'compiler_backend.dart';

final class Dart2JsBackend implements CompilerBackend {
  @override
  String get id => 'dart2js';

  @override
  Future<BackendOutput> build(BackendBuildRequest request) async {
    final workDir = p.dirname(request.facadePath);
    final compiledPath = p.join(workDir, 'out.dart.js');

    final dart = Platform.resolvedExecutable;
    final args = [
      'compile',
      'js',
      '-O2',
      '-o',
      compiledPath,
      request.facadePath,
    ];
    if (request.verbose) {
      stderr.writeln('[dart2js] ${[dart, ...args].join(' ')}');
    }
    final result = await Process.run(
      dart,
      args,
      workingDirectory: request.targetPackageRoot,
    );
    if (result.exitCode != 0) {
      throw BuildException(
        'dart compile js failed (exit ${result.exitCode}):\n'
        '${result.stdout}\n${result.stderr}',
      );
    }

    // Assemble the runtime artifact: Node preamble + compiled program, with
    // the source-map pointer stripped (the .map file is not shipped).
    final compiled = File(compiledPath)
        .readAsStringSync()
        .replaceAll(RegExp(r'^//# sourceMappingURL=.*$', multiLine: true), '');
    // The compiled program is a CommonJS script. Inside an ESM package
    // ("type": "module") a `.js` extension would make Node treat it as an ES
    // module and `require()` of it fails — `.cjs` is unambiguous.
    final runtimeName = switch (request.moduleFormat) {
      ModuleFormat.commonjs => '${request.artifactBaseName}.dart.js',
      ModuleFormat.esm => '${request.artifactBaseName}.dart.cjs',
    };
    File(p.join(request.outputDir, runtimeName)).writeAsStringSync(
      '${node_preamble.getPreamble(minified: true)}\n$compiled',
    );

    final entryName = 'index.js';
    final entrySource = switch (request.moduleFormat) {
      ModuleFormat.commonjs => _commonjsEntry(runtimeName),
      ModuleFormat.esm => _esmEntry(request, runtimeName),
    };
    File(p.join(request.outputDir, entryName)).writeAsStringSync(entrySource);

    return BackendOutput(
      emittedFiles: [entryName, runtimeName],
      packageJsonFields: {
        'type': switch (request.moduleFormat) {
          ModuleFormat.commonjs => 'commonjs',
          ModuleFormat.esm => 'module',
        },
        'engines': {'node': '>=18'},
      },
    );
  }

  String _commonjsEntry(String runtimeName) =>
      '''
"use strict";
// Generated by dart_typescript_builder — Node CommonJS entry (dart2js engine).
// The compiled Dart program installs its exports onto this module's exports
// via node_preamble.
module.exports = require("./$runtimeName");
''';

  String _esmEntry(BackendBuildRequest request, String runtimeName) {
    final names = request.api.exportedNames;
    final buffer = StringBuffer()
      ..writeln('// Generated by dart_typescript_builder — Node ESM entry '
          '(dart2js engine).')
      ..writeln('import { createRequire } from "node:module";')
      ..writeln('const require = createRequire(import.meta.url);')
      ..writeln('const \$exports = require("./$runtimeName");')
      ..writeln();
    for (final name in names) {
      buffer.writeln('export const $name = \$exports.$name;');
    }
    buffer
      ..writeln()
      ..writeln('export default \$exports;');
    return buffer.toString();
  }
}
