/// The WASM engine: `dart compile wasm` (WasmGC).
///
/// dart2wasm emits a `.wasm` module plus a `.mjs` init file exposing the
/// `compile(bytes) -> CompiledApp` / `app.instantiate(imports)` /
/// `instantiated.invokeMain()` API. `invokeMain()` runs the facade's `main`,
/// which installs the exports under a well-known key on `globalThis`
/// (under wasm, `dart:js_interop`'s `globalContext` IS the real `globalThis`).
///
/// WebAssembly instantiation is async, so the entry module uses top-level
/// `await` — the wasm engine is therefore ESM-only and needs Node >= 22
/// (WasmGC support).
library;

import 'dart:io';

import 'package:path/path.dart' as p;

import '../diagnostics.dart';
import 'compiler_backend.dart';

final class Dart2WasmBackend implements CompilerBackend {
  @override
  String get id => 'wasm';

  @override
  Future<BackendOutput> build(BackendBuildRequest request) async {
    if (request.moduleFormat == ModuleFormat.commonjs) {
      throw BuildException(
        'the wasm engine requires --module esm: WebAssembly instantiation is '
        'asynchronous and CommonJS cannot use top-level await.',
      );
    }

    final workDir = p.dirname(request.facadePath);
    final compiledWasm = p.join(workDir, 'out.wasm');

    final dart = Platform.resolvedExecutable;
    final args = [
      'compile',
      'wasm',
      '--no-source-maps',
      '-o',
      compiledWasm,
      request.facadePath,
    ];
    if (request.verbose) {
      stderr.writeln('[dart2wasm] ${[dart, ...args].join(' ')}');
    }
    final result = await Process.run(
      dart,
      args,
      workingDirectory: request.targetPackageRoot,
    );
    if (result.exitCode != 0) {
      throw BuildException(
        'dart compile wasm failed (exit ${result.exitCode}):\n'
        '${result.stdout}\n${result.stderr}',
      );
    }

    final base = request.artifactBaseName;
    final wasmName = '$base.wasm';
    final loaderName = '$base.mjs';
    File(compiledWasm).copySync(p.join(request.outputDir, wasmName));
    File(p.setExtension(compiledWasm, '.mjs'))
        .copySync(p.join(request.outputDir, loaderName));

    const entryName = 'index.js';
    File(p.join(request.outputDir, entryName))
        .writeAsStringSync(_esmEntry(request, wasmName, loaderName));

    return BackendOutput(
      emittedFiles: [entryName, wasmName, loaderName],
      packageJsonFields: {
        'type': 'module',
        'engines': {'node': '>=22'},
      },
    );
  }

  String _esmEntry(
    BackendBuildRequest request,
    String wasmName,
    String loaderName,
  ) {
    final buffer = StringBuffer()
      ..writeln('// Generated by dart_typescript_builder — Node ESM entry '
          '(wasm engine).')
      ..writeln('import { compile } from "./$loaderName";')
      ..writeln('import { readFile } from "node:fs/promises";')
      ..writeln()
      ..writeln('const bytes = await readFile('
          'new URL("./$wasmName", import.meta.url));')
      ..writeln('const app = await compile(bytes);')
      ..writeln('const instantiated = await app.instantiate({});')
      ..writeln('instantiated.invokeMain();')
      ..writeln()
      ..writeln('const \$exports = globalThis.${request.globalExportKey};')
      ..writeln('if (!\$exports) {')
      ..writeln('  throw new Error("${request.api.dartPackageName}: the Dart '
          'WASM module did not initialize its exports");')
      ..writeln('}')
      ..writeln();
    for (final name in request.api.exportedNames) {
      buffer.writeln('export const $name = \$exports.$name;');
    }
    buffer
      ..writeln()
      ..writeln('export default \$exports;');
    return buffer.toString();
  }
}
