// Generated by dart_typescript_builder — do not edit.
// TypeScript declarations for the compiled Dart package
// `async_logic` (package:async_logic/async_logic.dart).
//
// Boundary semantics:
// - Dart `int`, `double` and `num` all cross as JS `number`
//   (IEEE-754 double); integers beyond 2^53 lose precision.
// - Dart `DateTime` crosses as JS `Date` via epoch
//   milliseconds: microseconds are truncated and the Dart
//   local/UTC flag is not preserved (arrives in Dart as UTC).
// - `unknown` marks Dart `dynamic`/`Object`: only
//   JSON-compatible values survive the boundary.
// - Class instances are opaque handles over Dart objects;
//   only handles created by this package can be passed back.

/**
 * Applies a JS-supplied callback twice (JS function -> Dart function).
 */
export function applyTwice(seed: number, transform: (p0: number) => number): number;

/**
 * Emits `1..count` with a small delay (Dart stream -> JS AsyncIterable).
 */
export function counter(count: number): AsyncIterable<number>;

/**
 * A callback that receives a class instance (handles in callbacks).
 */
export function describeVia(ticket: Ticket, formatter: (p0: Ticket) => string): string;

/**
 * Returns a concrete [TicketFeed] through the abstract type.
 */
export function feedOf(owners: string[]): TicketFeed;

/**
 * Awaits an async (Promise-returning) callback.
 */
export function greetVia(loader: (p0: string) => Promise<string>): Promise<string>;

/**
 * Streams of class instances.
 */
export function issueTickets(owners: string[]): AsyncIterable<Ticket>;

/**
 * Returns a function to JS (Dart function -> JS function).
 */
export function makeAdder(base: number): (p0: number) => number;

/**
 * Sums a JS async iterable (JS AsyncIterable -> Dart stream).
 */
export function total(values: AsyncIterable<number>): Promise<number>;

/**
 * A simple resource with a stream-bearing contract.
 */
export interface Ticket {
  readonly owner: string;
  describe(): string;
}

/**
 * Creates a `Ticket` (Dart constructor `Ticket`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createTicket(owner: string): Ticket;

/**
 * A Stream-bearing abstract contract: since Phase 4 it has a runtime
 * wrapper too (instances returned by Dart are fully usable).
 */
export interface TicketFeed {
  watch(): AsyncIterable<Ticket>;
  close(): Promise<void>;
}
