/// Stage 4 of the pipeline: generate TypeScript declarations (`.d.ts`) from
/// the same [ApiModel] the facade was generated from, so the declared types
/// always match the *marshalled boundary* — never the raw Dart types.
library;

import 'model.dart';

/// Generates the `index.d.ts` contents for [api].
///
/// [firestoreTypes] only extends the boundary-semantics documentation: the
/// extra firebase-admin values all live inside `unknown` data, so no
/// declared type changes.
String generateDts(ApiModel api, {bool firestoreTypes = false}) {
  final buffer = StringBuffer()
    ..writeln('// Generated by dart_typescript_builder — do not edit.')
    ..writeln('// TypeScript declarations for the compiled Dart package')
    ..writeln('// `${api.dartPackageName}` (${api.libraryUri}).')
    ..writeln('//')
    ..writeln('// Boundary semantics:')
    ..writeln('// - Dart `int`, `double` and `num` all cross as JS `number`')
    ..writeln('//   (IEEE-754 double); integers beyond 2^53 lose precision.')
    ..writeln(
      api.usesFirestoreTimestamp
          ? '// - Dart `DateTime` crosses as a Firestore `Timestamp`\n'
                '//   (firebase-admin peer dependency), microsecond fidelity;\n'
                '//   the Dart local/UTC flag is not preserved (arrives UTC).'
          : '// - Dart `DateTime` crosses as JS `Date` via epoch\n'
                '//   milliseconds: microseconds are truncated and the Dart\n'
                '//   local/UTC flag is not preserved (arrives in Dart as UTC).',
    )
    ..writeln('// - `unknown` marks Dart `dynamic`/`Object`: only')
    ..writeln('//   JSON-compatible values survive the boundary.')
    ..writeln('// - Class instances are opaque handles over Dart objects;')
    ..writeln('//   only handles created by this package can be passed back.');

  if (firestoreTypes) {
    buffer
      ..writeln('// - Built with --firestore-types: inside `unknown` data,')
      ..writeln('//   Buffer/Uint8Array crosses as Dart Uint8List (copied,')
      ..writeln('//   returns as a fresh Uint8Array) and GeoPoint,')
      ..writeln('//   DocumentReference, FieldValue and VectorValue pass')
      ..writeln('//   through unchanged (identity preserved).');
  }

  if (api.usesFirestoreTimestamp) {
    buffer
      ..writeln()
      ..writeln('import type { Timestamp } from "firebase-admin/firestore";');
  }

  for (final enumApi in api.enums) {
    buffer.writeln();
    _writeDoc(buffer, enumApi.documentation, indent: '');
    buffer
      ..writeln('// Dart enum `${enumApi.name}`: values cross by name;')
      ..writeln('// enhanced-enum members stay Dart-side.')
      ..writeln('export type ${enumApi.name} = ${enumApi.tsUnion};');
  }

  for (final constant in api.constants) {
    buffer.writeln();
    _writeDoc(buffer, constant.documentation, indent: '');
    buffer.writeln('export const ${constant.name}: ${constant.type.tsSource};');
  }

  for (final function in api.functions) {
    buffer.writeln();
    _writeDoc(buffer, function.documentation, indent: '');
    buffer.writeln(
      'export function ${function.name}(${_parameterList(function)}): '
      '${function.returnType.tsSource};',
    );
  }

  for (final classApi in api.classes) {
    buffer.writeln();
    _writeDoc(buffer, classApi.documentation, indent: '');
    final extendsClause = classApi.extendsNames.isEmpty
        ? ''
        : ' extends ${classApi.extendsNames.join(', ')}';
    buffer.writeln('export interface ${classApi.name}$extendsClause {');
    for (final property in classApi.properties) {
      _writeDoc(buffer, property.documentation, indent: '  ');
      final readonly = property.isReadonly ? 'readonly ' : '';
      buffer.writeln('  $readonly${property.name}: ${property.type.tsSource};');
    }
    for (final method in classApi.methods) {
      _writeDoc(buffer, method.documentation, indent: '  ');
      buffer.writeln(
        '  ${method.name}(${_parameterList(method)}): '
        '${method.returnType.tsSource};',
      );
    }
    buffer.writeln('}');

    if (!classApi.isAbstract) {
      final ctor = FunctionApi(
        name: classApi.factoryName,
        parameters: classApi.constructorParameters,
        returnType: ClassRefType(classApi.name),
      );
      buffer
        ..writeln()
        ..writeln('/**')
        ..writeln(
          ' * Creates a `${classApi.name}` '
          '(Dart constructor `${classApi.name}`).',
        )
        ..writeln(' *')
        ..writeln(' * The returned value is an opaque handle to a Dart object,')
        ..writeln(' * not a plain JS object.')
        ..writeln(' */')
        ..writeln(
          'export function ${classApi.factoryName}'
          '(${_parameterList(ctor)}): ${classApi.name};',
        );
    }

    if (classApi.hasStaticsNamespace) {
      buffer
        ..writeln()
        ..writeln('/**')
        ..writeln(
          ' * Statics of the Dart class `${classApi.name}` '
          '(static methods, named',
        )
        ..writeln(' * constructors and factories, static constants).')
        ..writeln(' */')
        ..writeln('export const ${classApi.name}: {');
      for (final constant in classApi.staticProperties) {
        _writeDoc(buffer, constant.documentation, indent: '  ');
        buffer.writeln(
          '  readonly ${constant.name}: ${constant.type.tsSource};',
        );
      }
      for (final callable in classApi.staticCallables) {
        _writeDoc(buffer, callable.documentation, indent: '  ');
        buffer.writeln(
          '  ${callable.name}(${_parameterList(callable)}): '
          '${callable.returnType.tsSource};',
        );
      }
      buffer.writeln('};');
    }
  }

  return buffer.toString();
}

/// JS/TS reserved words are illegal as function-declaration parameter names.
/// Positional parameter names are pure labels (calls are positional), so
/// they can be safely renamed; named options are object members, where
/// reserved words are legal.
const _tsReservedParamNames = {
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'let',
  'static',
  'yield',
  'await',
  'arguments',
  'eval',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public',
};

String _paramLabel(String name) =>
    _tsReservedParamNames.contains(name) ? '${name}_' : name;

String _parameterList(FunctionApi function) {
  final parts = <String>[
    for (final p in function.requiredPositional)
      '${_paramLabel(p.name)}: ${p.type.tsSource}',
    for (final p in function.optionalPositional)
      '${_paramLabel(p.name)}?: ${p.type.tsSource}',
  ];
  if (function.hasOptionsObject) {
    final members = function.named
        .map((p) => '${p.name}${p.isRequired ? '' : '?'}: ${p.type.tsSource}')
        .join('; ');
    final optional = function.optionsObjectIsOptional ? '?' : '';
    parts.add('${function.optionsParameterName}$optional: { $members }');
  }
  return parts.join(', ');
}

/// Converts a Dart doc comment (`///` lines or a `/** ... */` block) into a
/// JSDoc block. `*/` inside doc text is escaped — it would otherwise close
/// the generated JSDoc early and inject the remaining text as raw
/// TypeScript source.
void _writeDoc(
  StringBuffer buffer,
  String? documentation, {
  required String indent,
}) {
  if (documentation == null || documentation.trim().isEmpty) return;
  final lines = documentation
      .split('\n')
      .map((line) => line.trim())
      .map((line) => line.startsWith('///') ? line.substring(3).trim() : line)
      // Block-style Dart docs: strip the comment markers themselves.
      .map((line) => line.startsWith('/**') ? line.substring(3).trim() : line)
      .map(
        (line) => line.endsWith('*/')
            ? line.substring(0, line.length - 2).trim()
            : line,
      )
      .map((line) => line.startsWith('*') ? line.substring(1).trim() : line)
      .map((line) => line.replaceAll('*/', r'*\/'))
      .toList();
  buffer.writeln('$indent/**');
  for (final line in lines) {
    buffer.writeln('$indent * $line'.trimRight());
  }
  buffer.writeln('$indent */');
}
