/// Stage 4 of the pipeline: generate TypeScript declarations (`.d.ts`) from
/// the same [ApiModel] the facade was generated from, so the declared types
/// always match the *marshalled boundary* — never the raw Dart types.
library;

import 'model.dart';

/// Generates the `index.d.ts` contents for [api].
String generateDts(ApiModel api) {
  final buffer = StringBuffer()
    ..writeln('// Generated by dart_typescript_builder — do not edit.')
    ..writeln('// TypeScript declarations for the compiled Dart package')
    ..writeln('// `${api.dartPackageName}` (${api.libraryUri}).')
    ..writeln('//')
    ..writeln('// Numeric caveat: Dart `int`, `double` and `num` all cross')
    ..writeln('// the boundary as JS `number` (IEEE-754 double). Integer')
    ..writeln('// values beyond 2^53 lose precision.');

  for (final function in api.functions) {
    buffer.writeln();
    _writeDoc(buffer, function.documentation, indent: '');
    buffer.writeln(
      'export function ${function.name}'
      '(${_parameterList(function.parameters)}): '
      '${function.returnType.tsSource};',
    );
  }

  for (final classApi in api.classes) {
    buffer.writeln();
    _writeDoc(buffer, classApi.documentation, indent: '');
    buffer.writeln('export interface ${classApi.name} {');
    for (final property in classApi.properties) {
      _writeDoc(buffer, property.documentation, indent: '  ');
      final readonly = property.isReadonly ? 'readonly ' : '';
      buffer.writeln('  $readonly${property.name}: ${property.type.tsSource};');
    }
    for (final method in classApi.methods) {
      _writeDoc(buffer, method.documentation, indent: '  ');
      buffer.writeln(
        '  ${method.name}(${_parameterList(method.parameters)}): '
        '${method.returnType.tsSource};',
      );
    }
    buffer
      ..writeln('}')
      ..writeln()
      ..writeln('/**')
      ..writeln(
        ' * Creates a `${classApi.name}` '
        '(Dart constructor `${classApi.name}`).',
      )
      ..writeln(' *')
      ..writeln(' * The returned value is an opaque handle to a Dart object,')
      ..writeln(' * not a plain JS object.')
      ..writeln(' */')
      ..writeln(
        'export function ${classApi.factoryName}'
        '(${_parameterList(classApi.constructorParameters)}): '
        '${classApi.name};',
      );
  }

  return buffer.toString();
}

String _parameterList(List<ParameterApi> parameters) => parameters
    .map((parameter) => '${parameter.name}: ${parameter.type.tsSource}')
    .join(', ');

/// Converts a Dart `///` doc comment into a JSDoc block.
void _writeDoc(
  StringBuffer buffer,
  String? documentation, {
  required String indent,
}) {
  if (documentation == null || documentation.trim().isEmpty) return;
  final lines = documentation
      .split('\n')
      .map((line) => line.trim())
      .map((line) => line.startsWith('///') ? line.substring(3).trim() : line)
      .toList();
  buffer.writeln('$indent/**');
  for (final line in lines) {
    buffer.writeln('$indent * $line'.trimRight());
  }
  buffer.writeln('$indent */');
}
