/// Stage 2 of the pipeline: generate the Dart `dart:js_interop` facade that
/// the compiler backend (dart2js or dart2wasm) will compile.
///
/// The facade is engine-agnostic: `dart:js_interop` is the compiler-neutral
/// interop layer, so the exact same generated source compiles under both
/// backends. Export delivery works on every target:
///
///  * Node CommonJS (dart2js + node_preamble): the preamble exposes the
///    module's `exports` object as `self.exports`; installing our exports
///    there makes the compiled file a real CommonJS module.
///  * WASM / browser: exports are installed under a well-known key on
///    `globalThis` for the entry module to pick up after `invokeMain()`.
library;

import 'model.dart';

/// Generates the facade entrypoint source for [api].
///
/// [globalExportKey] is the well-known `globalThis` property the exports
/// object is installed under (unique per npm package name).
String generateFacade(ApiModel api, {required String globalExportKey}) {
  final buffer = StringBuffer()
    ..writeln('// GENERATED BY dart_typescript_builder — DO NOT EDIT.')
    ..writeln('// dart:js_interop facade over ${api.libraryUri}.')
    ..writeln('// ignore_for_file: type=lint')
    ..writeln()
    ..writeln("import 'dart:js_interop';")
    ..writeln("import 'dart:js_interop_unsafe';")
    ..writeln()
    ..writeln("import '${api.libraryUri}' as \$target;")
    ..writeln();

  for (final classApi in api.classes) {
    _writeClassWrapper(buffer, classApi);
  }

  _writeInstall(buffer, api);

  buffer
    ..writeln('void main() {')
    ..writeln('  final exports = JSObject();')
    ..writeln('  _install(exports);')
    ..writeln('  // Node CommonJS: node_preamble exposes `module.exports` as')
    ..writeln('  // `self.exports`; installing there makes the compiled file')
    ..writeln('  // a require()-able module.')
    ..writeln("  final moduleExports = globalContext['exports'];")
    ..writeln('  if (moduleExports != null && moduleExports.isA<JSObject>()) {')
    ..writeln('    _install(moduleExports as JSObject);')
    ..writeln('  }')
    ..writeln('  // WASM / browser fallback: a well-known global key.')
    ..writeln("  globalContext['$globalExportKey'] = exports;")
    ..writeln('}');

  return buffer.toString();
}

void _writeClassWrapper(StringBuffer buffer, ClassApi classApi) {
  final wrapper = _wrapperName(classApi);
  buffer
    ..writeln('/// JS-facing wrapper for `${classApi.name}` — an opaque')
    ..writeln('/// handle exposing the class through generated accessors.')
    ..writeln('@JSExport()')
    ..writeln('final class $wrapper {')
    ..writeln('  $wrapper(this._inner);')
    ..writeln()
    ..writeln('  final \$target.${classApi.name} _inner;');

  for (final property in classApi.properties) {
    final type = property.type.dartSource;
    buffer
      ..writeln()
      ..writeln('  $type get ${property.name} => _inner.${property.name};');
    if (!property.isReadonly) {
      buffer
        ..writeln('  set ${property.name}($type value) {')
        ..writeln('    _inner.${property.name} = value;')
        ..writeln('  }');
    }
  }

  for (final method in classApi.methods) {
    final params = method.parameters
        .map((parameter) => '${parameter.type.dartSource} ${parameter.name}')
        .join(', ');
    final args = method.parameters
        .map((parameter) => parameter.name)
        .join(', ');
    buffer
      ..writeln()
      ..writeln(
        '  ${method.returnType.dartSource} ${method.name}($params) => '
        '_inner.${method.name}($args);',
      );
  }

  buffer
    ..writeln('}')
    ..writeln();
}

void _writeInstall(StringBuffer buffer, ApiModel api) {
  buffer.writeln('void _install(JSObject target) {');
  for (final function in api.functions) {
    final params = function.parameters
        .map((parameter) => '${parameter.type.dartSource} ${parameter.name}')
        .join(', ');
    final args = function.parameters
        .map((parameter) => parameter.name)
        .join(', ');
    final call = '\$target.${function.name}($args)';
    final closure = switch (function.returnType) {
      VoidType() => '($params) { $call; }',
      _ => '($params) => $call',
    };
    buffer.writeln("  target['${function.name}'] = ($closure).toJS;");
  }
  for (final classApi in api.classes) {
    final params = classApi.constructorParameters
        .map((parameter) => '${parameter.type.dartSource} ${parameter.name}')
        .join(', ');
    final args = classApi.constructorParameters
        .map((parameter) => parameter.name)
        .join(', ');
    buffer.writeln(
      "  target['${classApi.factoryName}'] = (($params) => "
      'createJSInteropWrapper(${_wrapperName(classApi)}('
      '\$target.${classApi.name}($args)))).toJS;',
    );
  }
  buffer
    ..writeln('}')
    ..writeln();
}

String _wrapperName(ClassApi classApi) => '_\$${classApi.name}Export';
