/// Stage 2 of the pipeline: generate the Dart `dart:js_interop` facade that
/// the compiler backend (dart2js or dart2wasm) will compile.
///
/// The facade is engine-agnostic and its shape is dictated by empirically
/// verified `js_interop` behavior (identical findings on dart2js AND
/// dart2wasm, Dart 3.12):
///
///  * Arity is unforgiving: a fixed-arity `.toJS` closure crashes when JS
///    omits trailing arguments, and a non-nullable Dart default value crashes
///    on an explicit `undefined`. Therefore EVERY closure parameter is
///    emitted as optional-positional `JSAny?` and all conversion/validation
///    happens in the body with readable `ArgumentError`s (boundary cast
///    failures on wasm surface as message-less `WebAssembly.Exception`s —
///    hostile to JS callers).
///  * `undefined` and `null` both arrive as Dart `null`.
///  * Class instances cross as opaque handles: a plain JS object carrying a
///    `JSBoxedDartObject` under `__dtb_handle__` (identity-preserving on
///    both engines; guarded by the precise `isA<JSBoxedDartObject>` brand
///    check) plus generated accessor properties and method closures.
///  * `dynamic` data is deep-converted by hand — NOT with `jsify`/`dartify`,
///    whose number semantics diverge between engines (wasm dartifies every
///    JS number to `double`). Whole numbers are normalized to `int`,
///    matching dart2js/web semantics on both engines.
///
/// Export delivery works on every target:
///
///  * Node CommonJS (dart2js + node_preamble): the preamble exposes the
///    module's `exports` object as `self.exports`; installing our exports
///    there makes the compiled file a real CommonJS module.
///  * WASM / browser: exports are installed under a well-known key on
///    `globalThis` for the entry module to pick up after `invokeMain()`.
library;

import 'dart:collection';

import 'model.dart';

/// Generates the facade entrypoint source for [api].
///
/// [globalExportKey] is the well-known `globalThis` property the exports
/// object is installed under (unique per npm package name).
///
/// With [firestoreTypes], `dynamic` data additionally marshals the full
/// firebase-admin Firestore value set: `Buffer`/`Uint8Array` <-> `Uint8List`
/// (copied), and identity-preserving pass-through for `GeoPoint`,
/// `DocumentReference`, `FieldValue` and `VectorValue`.
String generateFacade(
  ApiModel api, {
  required String globalExportKey,
  DateTimeMode dateTimeMode = DateTimeMode.jsDate,
  bool firestoreTypes = false,
}) {
  return _FacadeWriter(api, globalExportKey, dateTimeMode, firestoreTypes)
      .write();
}

final class _FacadeWriter {
  _FacadeWriter(this.api, this.globalExportKey, this.mode, this.firestoreTypes);

  final ApiModel api;
  final String globalExportKey;
  final DateTimeMode mode;
  final bool firestoreTypes;

  /// Memoized conversion helpers, keyed (and emitted) by name so goldens are
  /// stable.
  final SplayTreeMap<String, String> _helpers = SplayTreeMap();

  List<ClassApi> get _runtimeClasses => api.classes;

  /// Escapes a user identifier/label for embedding inside a single-quoted
  /// string literal of the GENERATED facade: `$` is legal in Dart
  /// identifiers and would otherwise interpolate against facade locals.
  static String _lit(String s) => s.replaceAll(r'$', r'\$');

  String write() {
    // Generate the bodies first so all needed helpers are registered.
    final wrappers = StringBuffer();
    for (final classApi in _runtimeClasses) {
      _writeClassWrapper(wrappers, classApi);
    }
    final install = _writeInstall();

    final buffer = StringBuffer()
      ..writeln('// GENERATED BY dart_typescript_builder — DO NOT EDIT.')
      ..writeln('// dart:js_interop facade over ${api.libraryUri}.')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln()
      ..writeln("import 'dart:async';")
      ..writeln("import 'dart:js_interop';")
      ..writeln("import 'dart:js_interop_unsafe';");
    if (firestoreTypes) {
      buffer.writeln("import 'dart:typed_data';");
    }
    buffer
      ..writeln()
      ..writeln("import '${api.libraryUri}' as \$target;")
      ..writeln()
      ..write(_plumbing())
      ..write(wrappers);
    for (final helper in _helpers.values) {
      buffer
        ..writeln(helper)
        ..writeln();
    }
    buffer
      ..write(install)
      ..writeln('void main() {')
      ..writeln('  final exports = JSObject();')
      ..writeln('  _install(exports);')
      ..writeln('  // Node CommonJS: node_preamble exposes `module.exports` as')
      ..writeln('  // `self.exports`; installing there makes the compiled file')
      ..writeln('  // a require()-able module.')
      ..writeln("  final moduleExports = globalContext['exports'];")
      ..writeln(
        '  if (moduleExports != null && moduleExports.isA<JSObject>()) {',
      )
      ..writeln('    _install(moduleExports as JSObject);')
      ..writeln('  }')
      ..writeln('  // WASM / browser fallback: a well-known global key.')
      ..writeln("  globalContext['$globalExportKey'] = exports;")
      ..writeln('}');
    return buffer.toString();
  }

  // --------------------------------------------------------------------
  // Fixed plumbing: JS externals, error reporting, options access,
  // DateTime bridging (per mode), and the deep `dynamic` converters.
  // --------------------------------------------------------------------

  String _plumbing() {
    final buffer = StringBuffer()
      ..writeln('''
@JS('Object.keys')
external JSArray<JSString> _objectKeys(JSObject object);

@JS('Object.defineProperty')
external void _definePropertyRaw(
  JSObject target,
  JSString name,
  JSObject descriptor,
);

@JS('Array.isArray')
external bool _isJsArray(JSAny? value);

@JS('Date')
extension type _JSDate._(JSObject _) implements JSObject {
  external _JSDate(int millisecondsSinceEpoch);
  external double getTime();
}

String _describe(JSAny? value) {
  if (value == null) return 'null';
  if (_isJsArray(value)) return 'an array';
  if (value.typeofEquals('string')) return 'a string';
  if (value.typeofEquals('number')) return 'a number';
  if (value.typeofEquals('boolean')) return 'a boolean';
  if (value.typeofEquals('function')) return 'a function';
  return 'a JS object';
}

// Injected by the package entry module. Boundary validation errors are
// thrown from a JS frame so they reach callers as real TypeErrors with a
// message — a Dart exception escaping a dart2wasm module surfaces as an
// opaque, message-less WebAssembly.Exception.
@JS('__dtb_throw__')
external JSFunction? get _jsThrower;

Never _throwBoundaryError(String message) {
  final thrower = _jsThrower;
  if (thrower != null) {
    thrower.callAsFunction(null, message.toJS);
  }
  throw ArgumentError(message);
}

Never _fail(String expected, JSAny? value) =>
    _throwBoundaryError('expected \$expected, got \${_describe(value)}');

void _defineGetter(JSObject target, String name, JSFunction getter) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

void _defineAccessor(
  JSObject target,
  String name,
  JSFunction getter,
  JSFunction setter,
) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['set'] = setter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

JSObject? _asOptions(JSAny? value, String owner) {
  if (value == null) return null;
  if (value.isA<JSObject>() && !_isJsArray(value)) return value as JSObject;
  _throwBoundaryError(
    "expected an options object for '\$owner', got \${_describe(value)}",
  );
}

// Own-property check: `has`/`in` walks the prototype chain, which would make
// options named after Object.prototype members (toString, constructor, ...)
// always look "present".
@JS('Object.hasOwn')
external bool _hasOwn(JSObject object, JSString name);

JSAny? _requireOption(JSObject? options, String name, String owner) {
  if (options == null || !_hasOwn(options, name.toJS)) {
    _throwBoundaryError("missing required option '\$name' of '\$owner'");
  }
  return options[name];
}

JSAny? _readOption(JSObject? options, String name) =>
    (options == null || !_hasOwn(options, name.toJS)) ? null : options[name];

/// Sets a map entry on an outgoing plain object. A key literally named
/// `__proto__` must go through defineProperty: plain assignment would
/// replace the object's prototype instead of storing the entry.
void _setEntry(JSObject target, String key, JSAny? value) {
  if (key == '__proto__') {
    final descriptor = JSObject();
    descriptor['value'] = value;
    descriptor['enumerable'] = true.toJS;
    descriptor['writable'] = true.toJS;
    descriptor['configurable'] = true.toJS;
    _definePropertyRaw(target, key.toJS, descriptor);
  } else {
    target[key] = value;
  }
}

/// Outgoing streams: a JS object implementing the async-iteration protocol.
/// `for await` works; an early `break` (protocol `return`) cancels the Dart
/// subscription.
JSObject _streamToJs<T>(Stream<T> stream, JSAny? Function(T) convert) {
  final iterable = JSObject();
  iterable.setProperty(JSSymbol.asyncIterator, (() {
    final iterator = StreamIterator<T>(stream);
    final jsIterator = JSObject();
    jsIterator['next'] = (() {
      return iterator.moveNext().then<JSAny?>((hasNext) {
        final result = JSObject();
        result['done'] = (!hasNext).toJS;
        result['value'] = hasNext ? convert(iterator.current) : null;
        return result;
      }).toJS;
    }).toJS;
    jsIterator['return'] = (([JSAny? value]) {
      final result = JSObject();
      result['done'] = true.toJS;
      unawaited(iterator.cancel());
      return result;
    }).toJS;
    return jsIterator;
  }).toJS);
  return iterable;
}

/// Incoming async iterables, pulled into a Dart stream.
Stream<T> _streamFromJs<T>(JSAny? value, T Function(JSAny?) convert) async* {
  final iterable = value as JSObject;
  final makeIterator = iterable.getProperty<JSFunction>(
    JSSymbol.asyncIterator,
  );
  final iterator = makeIterator.callAsFunction(iterable) as JSObject;
  final next = iterator.getProperty<JSFunction>('next'.toJS);
  while (true) {
    final result =
        await (next.callAsFunction(iterator) as JSPromise<JSAny?>).toDart
            as JSObject;
    if ((result['done'] as JSBoolean?)?.toDart ?? false) break;
    yield convert(result['value']);
  }
}

/// Builds a FRESH JS array. Never use `List.toJS` for outgoing values: on
/// dart2js it is a zero-copy cast and the Dart list's internal `\$ti`
/// type-info symbol would leak into consumer-visible arrays.
JSArray<JSAny?> _jsArrayOf(Iterable<JSAny?> items) {
  final result = JSArray<JSAny?>();
  var index = 0;
  for (final item in items) {
    result.setProperty((index++).toJS, item);
  }
  return result;
}
''');

    switch (mode) {
      case DateTimeMode.jsDate:
        buffer.writeln('''
JSAny? _dateTimeToJs(DateTime value) => _JSDate(value.millisecondsSinceEpoch);

bool _isJsDateTimeValue(JSAny? value) =>
    value != null && value.instanceOfString('Date');

DateTime _dateTimeFromJs(JSAny? value) {
  if (value != null && value.instanceOfString('Date')) {
    final milliseconds = (value as _JSDate).getTime();
    if (!milliseconds.isNaN) {
      return DateTime.fromMillisecondsSinceEpoch(
        milliseconds.toInt(),
        isUtc: true,
      );
    }
  }
  _fail('a JS Date', value);
}
''');
      case DateTimeMode.firestoreTimestamp:
        buffer.writeln('''
// Injected by the package entry module (index.js) from
// firebase-admin/firestore before the Dart program initializes.
@JS('__dtb_Timestamp__')
external JSAny? get _timestampClass;

@JS('__dtb_Timestamp__')
extension type _FsTimestamp._(JSObject _) implements JSObject {
  external _FsTimestamp(int seconds, int nanoseconds);
  external int get seconds;
  external int get nanoseconds;
}

bool _isFsTimestamp(JSAny? value) {
  if (value == null || !value.isA<JSObject>()) return false;
  final timestampClass = _timestampClass;
  if (timestampClass != null &&
      timestampClass.isA<JSFunction>() &&
      value.instanceof(timestampClass as JSFunction)) {
    return true;
  }
  // A Timestamp from a different firebase-admin copy: duck-check the
  // Timestamp contract instead of the identity of the class.
  final object = value as JSObject;
  return object.has('seconds') &&
      object.has('nanoseconds') &&
      object.has('toMillis');
}

bool _isJsDateTimeValue(JSAny? value) =>
    _isFsTimestamp(value) ||
    (value != null && value.instanceOfString('Date'));

JSAny? _dateTimeToJs(DateTime value) {
  if (_timestampClass == null) {
    _throwBoundaryError(
      'firebase-admin Timestamp is not available: load this package through '
      'its entry module (index.js), which injects it.',
    );
  }
  final microseconds = value.microsecondsSinceEpoch;
  var seconds = microseconds ~/ 1000000;
  var remainder = microseconds - seconds * 1000000;
  if (remainder < 0) {
    seconds -= 1;
    remainder += 1000000;
  }
  return _FsTimestamp(seconds, remainder * 1000);
}

DateTime _dateTimeFromJs(JSAny? value) {
  if (_isFsTimestamp(value)) {
    final timestamp = value as _FsTimestamp;
    return DateTime.fromMicrosecondsSinceEpoch(
      timestamp.seconds * 1000000 + timestamp.nanoseconds ~/ 1000,
      isUtc: true,
    );
  }
  // Graceful: accept a plain JS Date where a Timestamp is expected.
  if (value != null && value.instanceOfString('Date')) {
    final milliseconds = (value as _JSDate).getTime();
    if (!milliseconds.isNaN) {
      return DateTime.fromMillisecondsSinceEpoch(
        milliseconds.toInt(),
        isUtc: true,
      );
    }
  }
  _fail('a Firestore Timestamp', value);
}
''');
    }

    if (firestoreTypes) {
      buffer.writeln('''
// --firestore-types: the full firebase-admin Firestore value set crosses
// inside `dynamic` data. The classes are injected by the package entry
// module; any of them may be null when the installed firebase-admin does
// not export it (older versions) — the duck-typed checks below still catch
// GeoPoint and document references from foreign firebase-admin copies.
@JS('__dtb_GeoPoint__')
external JSAny? get _geoPointClass;

@JS('__dtb_DocumentReference__')
external JSAny? get _documentReferenceClass;

@JS('__dtb_FieldValue__')
external JSAny? get _fieldValueClass;

@JS('__dtb_VectorValue__')
external JSAny? get _vectorValueClass;

/// Identity-preserving holder for a Firestore value with no Dart
/// counterpart (GeoPoint, DocumentReference, FieldValue, VectorValue).
/// Dart code can carry it inside dynamic data and hand it back; the exact
/// same JS object is restored when the value crosses back to JS.
final class _FirestoreValue {
  _FirestoreValue(this.js);

  final JSObject js;

  @override
  String toString() => 'FirestoreValue<\${_jsConstructorName(js)}>';
}

String _jsConstructorName(JSObject object) {
  final ctor = object['constructor'];
  if (ctor != null && ctor.isA<JSObject>()) {
    final name = (ctor as JSObject)['name'];
    if (name != null && name.typeofEquals('string')) {
      return (name as JSString).toDart;
    }
  }
  return 'unknown';
}

bool _fsInstanceOf(JSAny value, JSAny? jsClass) =>
    jsClass != null &&
    jsClass.isA<JSFunction>() &&
    value.instanceof(jsClass as JSFunction);

bool _isFsPassthroughValue(JSAny? value) {
  if (value == null || !value.isA<JSObject>()) return false;
  if (_fsInstanceOf(value, _geoPointClass) ||
      _fsInstanceOf(value, _documentReferenceClass) ||
      _fsInstanceOf(value, _fieldValueClass) ||
      _fsInstanceOf(value, _vectorValueClass)) {
    return true;
  }
  // Values from a different firebase-admin copy: duck-check the stable
  // contracts. FieldValue/VectorValue sentinels have no usable duck
  // surface — those need the injected class identity above.
  final object = value as JSObject;
  if (object.has('latitude') &&
      object.has('longitude') &&
      object.has('isEqual')) {
    return true; // GeoPoint
  }
  if (object.has('firestore') && object.has('path') && object.has('id')) {
    return true; // DocumentReference (or CollectionReference)
  }
  return false;
}

// Also matches Node's Buffer — a Uint8Array subclass, and what
// firebase-admin returns for `bytes` document fields.
bool _isJsUint8Array(JSAny? value) =>
    value != null && value.instanceOfString('Uint8Array');
''');
    }

    // Deep converters for `dynamic` / `Object` values. Never uses
    // jsify/dartify: number semantics diverge between engines there.
    buffer.writeln('''
JSAny? _dynamicToJs(Object? value) =>
    _dynamicToJsRec(value, Set<Object>.identity());
''');
    buffer.writeln('JSAny? _dynamicToJsRec(Object? value, Set<Object> seen) {');
    buffer.writeln('''
  if (value == null) return null;
  if (value is bool) return value.toJS;
  if (value is num) return value.toJS;
  if (value is String) return value.toJS;
  if (value is DateTime) return _dateTimeToJs(value);''');
    if (firestoreTypes) {
      buffer.writeln('''
  if (value is _FirestoreValue) return value.js;
  // Before the Iterable branch: a Uint8List is also an Iterable<int>.
  if (value is Uint8List) return Uint8List.fromList(value).toJS;''');
    }
    for (final classApi in _runtimeClasses) {
      buffer.writeln(
        '  if (value is \$target.${classApi.name}) '
        'return _wrap_${classApi.name}(value);',
      );
    }
    buffer.writeln('''
  if (value is Enum) {
    _throwBoundaryError(
      'enum values cannot cross inside dynamic data '
      '(\${value.runtimeType}); use a typed API',
    );
  }
  if (value is Map) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = JSObject();
    value.forEach((key, item) {
      if (key is! String) {
        _throwBoundaryError(
          'only String map keys cross the boundary, '
          'got a key of type \${key.runtimeType}',
        );
      }
      _setEntry(result, key, _dynamicToJsRec(item, seen));
    });
    seen.remove(value);
    return result;
  }
  if (value is Iterable) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = _jsArrayOf(value.map((item) => _dynamicToJsRec(item, seen)));
    seen.remove(value);
    return result;
  }
  _throwBoundaryError(
    'cannot marshal a value of type \${value.runtimeType} across the '
    'boundary',
  );
}

Object? _dynamicFromJs(JSAny? value) {
  if (value == null) return null;
  if (value.typeofEquals('boolean')) return (value as JSBoolean).toDart;
  if (value.typeofEquals('number')) {
    final number = (value as JSNumber).toDartDouble;
    // Whole numbers become int, matching dart2js/web semantics on both
    // engines (2^53 guards against precision-lossy conversions).
    return (number.isFinite &&
            number.truncateToDouble() == number &&
            number.abs() <= 9007199254740992)
        ? number.toInt()
        : number;
  }
  if (value.typeofEquals('string')) return (value as JSString).toDart;
  if (_isJsArray(value)) {
    return [
      for (final item in (value as JSArray<JSAny?>).toDart)
        _dynamicFromJs(item),
    ];
  }
  if (_isJsDateTimeValue(value)) return _dateTimeFromJs(value);''');
    if (firestoreTypes) {
      buffer.writeln('''
  if (_isJsUint8Array(value)) {
    return Uint8List.fromList((value as JSUint8Array).toDart);
  }
  if (_isFsPassthroughValue(value)) return _FirestoreValue(value as JSObject);''');
    }
    buffer.writeln('''
  if (value.typeofEquals('function')) {
    _fail('a marshallable value (functions cannot cross the boundary)', value);
  }
  if (value.isA<JSObject>()) {
    final object = value as JSObject;
    final handle = object['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      return (handle as JSBoxedDartObject).toDart;
    }
    return <String, dynamic>{
      for (final key in _objectKeys(object).toDart.map((k) => k.toDart))
        key: _dynamicFromJs(object[key]),
    };
  }
  _fail('a marshallable value', value);
}
''');
    return buffer.toString();
  }

  // --------------------------------------------------------------------
  // Per-class wrappers: opaque handle + accessors + method closures.
  // --------------------------------------------------------------------

  void _writeClassWrapper(StringBuffer buffer, ClassApi classApi) {
    final name = classApi.name;
    // Role prefixes end in '_' so generated names cannot collide across
    // classes (`Foo` vs `CacheFoo` style overlaps).
    buffer
      ..writeln('final Expando<JSObject> _wrapCache_$name = Expando();')
      ..writeln()
      ..writeln('/// Opaque JS handle over `$name` (identity-cached).')
      ..writeln('JSObject _wrap_$name(\$target.$name inner) {');
    // Polymorphic dispatch: a supertype-typed value gets the wrapper of its
    // most-derived exported class (each subclass wrapper dispatches on).
    for (final subclass in api.directSubclassesOf(name)) {
      buffer.writeln(
        '  if (inner is \$target.${subclass.name}) '
        'return _wrap_${subclass.name}(inner);',
      );
    }
    buffer
      ..writeln('  final cached = _wrapCache_$name[inner];')
      ..writeln('  if (cached != null) return cached;')
      ..writeln('  final wrapper = JSObject();')
      ..writeln('  _wrapCache_$name[inner] = wrapper;')
      ..writeln("  wrapper['__dtb_handle__'] = inner.toJSBox;");
    for (final property in classApi.allProperties) {
      final getter =
          '(() => ${_toJs(property.type, 'inner.${property.name}')}).toJS';
      if (property.isReadonly) {
        buffer.writeln(
          "  _defineGetter(wrapper, '${_lit(property.name)}', $getter);",
        );
      } else {
        buffer
          ..writeln("  _defineAccessor(")
          ..writeln("    wrapper,")
          ..writeln("    '${_lit(property.name)}',")
          ..writeln('    $getter,')
          ..writeln('    ((JSAny? value) {')
          ..writeln(
            '      inner.${property.name} = '
            "${_toDart(property.type, 'value')};",
          )
          ..writeln('    }).toJS,')
          ..writeln('  );');
      }
    }
    for (final method in classApi.allMethods) {
      buffer.writeln(
        "  wrapper['${_lit(method.name)}'] = "
        '${_closure(method, '$name.${method.name}', (args) => 'inner.${method.name}($args)')}.toJS;',
      );
    }
    buffer
      ..writeln('  return wrapper;')
      ..writeln('}')
      ..writeln()
      ..writeln('\$target.$name _unwrap_$name(JSAny? value) {')
      ..writeln('  if (value != null && value.isA<JSObject>()) {')
      ..writeln("    final handle = (value as JSObject)['__dtb_handle__'];")
      ..writeln('    if (handle != null && handle.isA<JSBoxedDartObject>()) {')
      ..writeln('      final inner = (handle as JSBoxedDartObject).toDart;')
      ..writeln('      if (inner is \$target.$name) return inner;')
      ..writeln('    }')
      ..writeln('  }')
      ..writeln(
        "  _fail('a ${_lit(name)} handle created by this package', value);",
      )
      ..writeln('}')
      ..writeln();
  }

  // --------------------------------------------------------------------
  // _install: exports object population.
  // --------------------------------------------------------------------

  String _writeInstall() {
    final buffer = StringBuffer()..writeln('void _install(JSObject target) {');
    for (final constant in api.constants) {
      buffer.writeln(
        "  target['${_lit(constant.name)}'] = "
        "${_toJs(constant.type, '\$target.${constant.name}')};",
      );
    }
    for (final function in api.functions) {
      buffer.writeln(
        "  target['${_lit(function.name)}'] = "
        '${_closure(function, function.name, (args) => '\$target.${function.name}($args)')}.toJS;',
      );
    }
    for (final classApi in api.classes) {
      final name = classApi.name;
      if (!classApi.isAbstract) {
        final factory = FunctionApi(
          name: classApi.factoryName,
          parameters: classApi.constructorParameters,
          returnType: ClassRefType(name),
        );
        buffer.writeln(
          "  target['${_lit(classApi.factoryName)}'] = "
          '${_closure(factory, classApi.factoryName, (args) => '\$target.$name($args)')}.toJS;',
        );
      }
      if (classApi.hasStaticsNamespace) {
        buffer.writeln('  {');
        buffer.writeln('    final namespace = JSObject();');
        for (final property in classApi.staticProperties) {
          buffer.writeln(
            "    _defineGetter(namespace, '${_lit(property.name)}', "
            "(() => ${_toJs(property.type, '\$target.$name.${property.name}')}).toJS);",
          );
        }
        for (final callable in classApi.staticCallables) {
          buffer.writeln(
            "    namespace['${_lit(callable.name)}'] = "
            '${_closure(callable, '$name.${callable.name}', (args) => '\$target.$name.${callable.name}($args)')}.toJS;',
          );
        }
        buffer
          ..writeln("    target['${_lit(name)}'] = namespace;")
          ..writeln('  }');
      }
    }
    buffer
      ..writeln('}')
      ..writeln();
    return buffer.toString();
  }

  /// Builds an arity-tolerant closure for [function]: every parameter is
  /// optional-positional `JSAny?` (omitted / `undefined` / `null` all arrive
  /// as Dart null) and validation happens in the body with readable errors.
  String _closure(
    FunctionApi function,
    String label,
    String Function(String args) invoke,
  ) {
    final positional = [
      ...function.requiredPositional,
      ...function.optionalPositional,
    ];
    final jsParams = <String>[
      for (var i = 0; i < positional.length; i++) 'JSAny? \$a$i',
      if (function.hasOptionsObject) 'JSAny? \$options',
    ];
    final signature = jsParams.isEmpty ? '()' : '([${jsParams.join(', ')}])';

    final body = StringBuffer();
    if (function.hasOptionsObject) {
      body.writeln(
        "    final \$opts = _asOptions(\$options, '${_lit(label)}');",
      );
    }

    final args = <String>[];
    for (var i = 0; i < positional.length; i++) {
      final parameter = positional[i];
      args.add(_argument(parameter, '\$a$i', label, body, 'p$i'));
    }
    for (var i = 0; i < function.named.length; i++) {
      final parameter = function.named[i];
      final String source;
      if (parameter.isRequired) {
        source =
            "_requireOption(\$opts, '${_lit(parameter.name)}', "
            "'${_lit(label)}')";
      } else {
        source = "_readOption(\$opts, '${_lit(parameter.name)}')";
      }
      args.add(
        '${parameter.name}: '
        '${_argument(parameter, source, label, body, 'o$i')}',
      );
    }

    final call = invoke(args.join(', '));
    if (function.returnType is VoidType) {
      body.writeln('    $call;');
    } else {
      body.writeln('    return ${_toJs(function.returnType, call)};');
    }
    return '($signature {\n$body  })';
  }

  /// Converts one incoming argument, honoring inlinable literal defaults
  /// (bound through a typed local so collection literals get their element
  /// types from context).
  String _argument(
    ParameterApi parameter,
    String source,
    String label,
    StringBuffer body,
    String slot,
  ) {
    final defaultCode = parameter.defaultValueCode;
    if (defaultCode == null) return _toDart(parameter.type, source);
    final local = '\$$slot';
    body
      ..writeln('    final JSAny? ${local}Raw = $source;')
      ..writeln(
        '    final ${_dartType(parameter.type)} $local = ${local}Raw == null'
        '\n        ? $defaultCode'
        '\n        : ${_toDart(parameter.type, '${local}Raw')};',
      );
    return local;
  }

  // --------------------------------------------------------------------
  // Type conversion expressions + memoized helpers.
  // --------------------------------------------------------------------

  /// Dart spelling of [type] as usable inside the facade (target-package
  /// classes are `$target.`-qualified).
  String _dartType(BoundaryType type) {
    if (type is DynamicType) return type.dartSpelling;
    final core = switch (type) {
      PrimitiveType(:final kind) => kind.dartSource,
      VoidType() => 'void',
      DynamicType() => throw StateError('unreachable'),
      ListType(:final element, :final isIterable) =>
        '${isIterable ? 'Iterable' : 'List'}<${_dartType(element)}>',
      MapType(:final value) => 'Map<String, ${_dartType(value)}>',
      FutureType(:final value) => 'Future<${_dartType(value)}>',
      StreamType(:final value) => 'Stream<${_dartType(value)}>',
      DateTimeType() => 'DateTime',
      ClassRefType(:final className) => '\$target.$className',
      EnumType(:final enumName) => '\$target.$enumName',
      CallbackType(:final parameters, :final returnType) =>
        '${_dartType(returnType)} Function('
            '${parameters.map(_dartType).join(', ')})',
    };
    return type.isNullable ? '$core?' : core;
  }

  /// Expression converting the JS value [expr] to the Dart type [type].
  String _toDart(BoundaryType type, String expr) {
    switch (type) {
      case DynamicType(dartSpelling: 'Object'):
        return '${_registerToDartObject()}($expr)';
      case DynamicType():
        return '_dynamicFromJs($expr)';
      case VoidType():
        throw StateError('void cannot be a parameter type');
      case DateTimeType(isNullable: false):
        return '_dateTimeFromJs($expr)';
      case ClassRefType(:final className, isNullable: false):
        return '_unwrap_$className($expr)';
      default:
        return '${_registerToDart(type)}($expr)';
    }
  }

  /// Expression converting the Dart value [expr] to a JS value.
  String _toJs(BoundaryType type, String expr) {
    switch (type) {
      case PrimitiveType(isNullable: false):
        return '$expr.toJS';
      case PrimitiveType():
        return '$expr?.toJS';
      case DynamicType():
        return '_dynamicToJs($expr)';
      case VoidType():
        throw StateError('void has no value to convert');
      case DateTimeType(isNullable: false):
        return '_dateTimeToJs($expr)';
      case ClassRefType(:final className, isNullable: false):
        return '_wrap_$className($expr)';
      case EnumType(isNullable: false):
        return '$expr.name.toJS';
      default:
        return '${_registerToJs(type)}($expr)';
    }
  }

  String _registerToDartObject() {
    const name = '_toDartObject';
    _helpers.putIfAbsent(
      name,
      () =>
          'Object $name(JSAny? value) =>\n'
          "    _dynamicFromJs(value) ?? _fail('a non-null value', value);",
    );
    return name;
  }

  String _registerToDart(BoundaryType type) {
    final name = '_toDart${type.mangled}';
    if (_helpers.containsKey(name)) return name;
    _helpers[name] = ''; // claim before recursing (cycle guard)

    final String source;
    if (type.isNullable) {
      final core = _withoutNullability(type);
      source =
          '${_dartType(type)} $name(JSAny? value) =>\n'
          '    value == null ? null : ${_toDart(core, 'value')};';
    } else {
      source = switch (type) {
        PrimitiveType(:final kind) => switch (kind) {
          PrimitiveKind.string =>
            'String $name(JSAny? value) =>\n'
                "    value != null && value.typeofEquals('string')\n"
                '    ? (value as JSString).toDart\n'
                "    : _fail('a string', value);",
          PrimitiveKind.boolean =>
            'bool $name(JSAny? value) =>\n'
                "    value != null && value.typeofEquals('boolean')\n"
                '    ? (value as JSBoolean).toDart\n'
                "    : _fail('a boolean', value);",
          PrimitiveKind.intNumber =>
            'int $name(JSAny? value) {\n'
                "  if (value == null || !value.typeofEquals('number')) {\n"
                "    _fail('a number', value);\n"
                '  }\n'
                '  final number = (value as JSNumber).toDartDouble;\n'
                '  if (!number.isFinite ||\n'
                '      number.truncateToDouble() != number ||\n'
                '      number.abs() > 9007199254740992) {\n'
                "    _fail('a safe integer (|n| <= 2^53)', value);\n"
                '  }\n'
                '  return number.toInt();\n'
                '}',
          PrimitiveKind.doubleNumber =>
            'double $name(JSAny? value) =>\n'
                "    value != null && value.typeofEquals('number')\n"
                '    ? (value as JSNumber).toDartDouble\n'
                "    : _fail('a number', value);",
          PrimitiveKind.numNumber =>
            'num $name(JSAny? value) {\n'
                "  if (value == null || !value.typeofEquals('number')) {\n"
                "    _fail('a number', value);\n"
                '  }\n'
                '  final number = (value as JSNumber).toDartDouble;\n'
                '  return (number.isFinite &&\n'
                '          number.truncateToDouble() == number &&\n'
                '          number.abs() <= 9007199254740992)\n'
                '      ? number.toInt()\n'
                '      : number;\n'
                '}',
        },
        ListType(:final element) =>
          'List<${_dartType(element)}> $name(JSAny? value) {\n'
              '  if (value == null || !_isJsArray(value)) {\n'
              "    _fail('an array', value);\n"
              '  }\n'
              '  return [\n'
              '    for (final item in (value as JSArray<JSAny?>).toDart)\n'
              '      ${_toDart(element, 'item')},\n'
              '  ];\n'
              '}',
        MapType(value: final valueType) =>
          'Map<String, ${_dartType(valueType)}> $name(JSAny? value) {\n'
              '  if (value == null || !value.isA<JSObject>() || _isJsArray(value)) {\n'
              "    _fail('a plain object', value);\n"
              '  }\n'
              '  final object = value as JSObject;\n'
              '  return {\n'
              '    for (final key in _objectKeys(object).toDart.map((k) => k.toDart))\n'
              '      key: ${_toDart(valueType, 'object[key]')},\n'
              '  };\n'
              '}',
        FutureType(value: VoidType()) =>
          'Future<void> $name(JSAny? value) {\n'
              '  if (value == null || !value.isA<JSPromise>()) {\n'
              "    _fail('a Promise', value);\n"
              '  }\n'
              '  return (value as JSPromise<JSAny?>).toDart;\n'
              '}',
        FutureType(:final value) =>
          'Future<${_dartType(value)}> $name(JSAny? value) {\n'
              '  if (value == null || !value.isA<JSPromise>()) {\n'
              "    _fail('a Promise', value);\n"
              '  }\n'
              '  return (value as JSPromise<JSAny?>)\n'
              '      .toDart\n'
              '      .then((result) => ${_toDart(value, 'result')});\n'
              '}',
        StreamType(value: final valueType) =>
          'Stream<${_dartType(valueType)}> $name(JSAny? value) {\n'
              '  if (value == null ||\n'
              '      !value.isA<JSObject>() ||\n'
              '      (value as JSObject).getProperty<JSAny?>(\n'
              '            JSSymbol.asyncIterator,\n'
              '          ) ==\n'
              '          null) {\n'
              "    _fail('an async iterable', value);\n"
              '  }\n'
              '  return _streamFromJs<${_dartType(valueType)}>(\n'
              '    value,\n'
              '    (item) => ${_toDart(valueType, 'item')},\n'
              '  );\n'
              '}',
        EnumType(:final enumName) => _enumToDartHelper(name, enumName),
        CallbackType(:final parameters, :final returnType) =>
          _callbackToDartHelper(name, parameters, returnType),
        _ => throw StateError('no toDart helper for $type'),
      };
    }
    _helpers[name] = source;
    return name;
  }

  String _enumToDartHelper(String name, String enumName) {
    final values = api.enumByName(enumName)?.values ?? const <String>[];
    final union = values.map((v) => "'${_lit(v)}'").join(' | ');
    return '\$target.$enumName $name(JSAny? value) {\n'
        "  if (value != null && value.typeofEquals('string')) {\n"
        '    final name = (value as JSString).toDart;\n'
        '    for (final option in \$target.$enumName.values) {\n'
        '      if (option.name == name) return option;\n'
        '    }\n'
        '  }\n'
        '  _fail("one of $union", value);\n'
        '}';
  }

  /// JS function -> Dart function: arguments convert Dart -> JS, the result
  /// converts back (a Promise result becomes a Future for async callbacks).
  String _callbackToDartHelper(
    String name,
    List<BoundaryType> parameters,
    BoundaryType returnType,
  ) {
    final params = [
      for (var i = 0; i < parameters.length; i++)
        '${_dartType(parameters[i])} p$i',
    ].join(', ');
    final args = [
      'null',
      for (var i = 0; i < parameters.length; i++) _toJs(parameters[i], 'p$i'),
    ].join(', ');
    final call = "fn.callMethodVarArgs<JSAny?>('call'.toJS, [$args])";
    final body = returnType is VoidType
        ? '($params) {\n    $call;\n  }'
        : '($params) => ${_toDart(returnType, call)}';
    return '${_dartType(returnType)} Function($params) $name(JSAny? value) {\n'
        "  if (value == null || !value.typeofEquals('function')) {\n"
        "    _fail('a function', value);\n"
        '  }\n'
        '  final fn = value as JSFunction;\n'
        '  return $body;\n'
        '}';
  }

  String _registerToJs(BoundaryType type) {
    final name = '_toJs${type.mangled}';
    if (_helpers.containsKey(name)) return name;
    _helpers[name] = ''; // claim before recursing (cycle guard)

    final String source;
    if (type.isNullable) {
      final core = _withoutNullability(type);
      source =
          'JSAny? $name(${_dartType(type)} value) =>\n'
          '    value == null ? null : ${_toJs(core, 'value')};';
    } else {
      source = switch (type) {
        ListType(:final element) =>
          // Iterable-typed param accepts both List and Iterable sources.
          'JSAny? $name(Iterable<${_dartType(element)}> value) =>\n'
              '    _jsArrayOf(value.map((item) => ${_toJs(element, 'item')}));',
        MapType(:final value) =>
          'JSAny? $name(Map<String, ${_dartType(value)}> value) {\n'
              '  final result = JSObject();\n'
              '  value.forEach((key, item) {\n'
              '    _setEntry(result, key, ${_toJs(value, 'item')});\n'
              '  });\n'
              '  return result;\n'
              '}',
        FutureType(value: VoidType()) =>
          'JSAny? $name(Future<void> value) => value.toJS;',
        FutureType(:final value) =>
          'JSAny? $name(Future<${_dartType(value)}> value) =>\n'
              '    value.then<JSAny?>((result) => ${_toJs(value, 'result')}).toJS;',
        StreamType(value: final valueType) =>
          'JSAny? $name(Stream<${_dartType(valueType)}> value) =>\n'
              '    _streamToJs<${_dartType(valueType)}>(\n'
              '      value,\n'
              '      (item) => ${_toJs(valueType, 'item')},\n'
              '    );',
        CallbackType(:final parameters, :final returnType) =>
          _callbackToJsHelper(name, parameters, returnType),
        _ => throw StateError('no toJs helper for $type'),
      };
    }
    _helpers[name] = source;
    return name;
  }

  /// Dart function -> JS function: an arity-tolerant closure converting each
  /// argument JS -> Dart and the result back.
  String _callbackToJsHelper(
    String name,
    List<BoundaryType> parameters,
    BoundaryType returnType,
  ) {
    final params = [
      for (var i = 0; i < parameters.length; i++)
        '${_dartType(parameters[i])} p$i',
    ].join(', ');
    final jsParams = [
      for (var i = 0; i < parameters.length; i++) 'JSAny? \$a$i',
    ].join(', ');
    final signature = jsParams.isEmpty ? '()' : '([$jsParams])';
    final args = [
      for (var i = 0; i < parameters.length; i++)
        _toDart(parameters[i], '\$a$i'),
    ].join(', ');
    final body = returnType is VoidType
        ? '($signature {\n      value($args);\n    })'
        : '($signature => ${_toJs(returnType, 'value($args)')})';
    return 'JSAny? $name(${_dartType(returnType)} Function($params) value) =>\n'
        '    $body.toJS;';
  }

  BoundaryType _withoutNullability(BoundaryType type) => switch (type) {
    PrimitiveType(:final kind) => PrimitiveType(kind),
    DateTimeType(:final mode) => DateTimeType(mode: mode),
    ClassRefType(:final className) => ClassRefType(className),
    EnumType(:final enumName) => EnumType(enumName),
    CallbackType(:final parameters, :final returnType) => CallbackType(
      parameters,
      returnType,
    ),
    ListType(:final element, :final isIterable) => ListType(
      element,
      isIterable: isIterable,
    ),
    MapType(:final value) => MapType(value),
    FutureType(:final value) => FutureType(value),
    StreamType(:final value) => StreamType(value),
    DynamicType() || VoidType() => type,
  };
}
