/// Stage 5 of the pipeline: assemble the installable npm package —
/// `package.json`, `index.d.ts`, a consumer README — around the runtime
/// files the compiler backend emitted.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'api_analyzer.dart';
import 'backend/compiler_backend.dart';
import 'dts_generator.dart';
import 'model.dart';

final class PackageResult {
  const PackageResult({required this.outputDir, required this.files});

  final String outputDir;

  /// File names relative to [outputDir].
  final List<String> files;
}

/// Writes `package.json`, `index.d.ts` and `README.md` into
/// [outputDir], merging the backend's required fields.
PackageResult writeNpmPackage({
  required String outputDir,
  required String npmName,
  required TargetPackageInfo target,
  required ApiModel api,
  required BackendOutput backendOutput,
  required String engineId,
  bool firestoreTypes = false,
}) {
  final dts = generateDts(api, firestoreTypes: firestoreTypes);
  File(p.join(outputDir, 'index.d.ts')).writeAsStringSync(dts);

  final packageJson = <String, Object?>{
    'name': npmName,
    'version': _npmVersion(target.version),
    'description':
        '${target.description ?? 'Compiled Dart package ${target.name}.'} '
        '(Compiled from Dart with dart_typescript_builder, engine: '
        '$engineId.)',
    'main': 'index.js',
    'types': 'index.d.ts',
    'exports': {
      '.': {'types': './index.d.ts', 'default': './index.js'},
    },
    'files': [...backendOutput.emittedFiles, 'index.d.ts', 'README.md'],
    // --firestore-types needs the injection even when no DateTime appears
    // in the API surface itself.
    if (api.usesFirestoreTimestamp || firestoreTypes)
      'peerDependencies': {'firebase-admin': '>=11'},
    ...backendOutput.packageJsonFields,
  };
  File(p.join(outputDir, 'package.json')).writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(packageJson)}\n',
  );

  File(p.join(outputDir, 'README.md')).writeAsStringSync(
    _readme(npmName, target, api, engineId, firestoreTypes: firestoreTypes),
  );

  return PackageResult(
    outputDir: outputDir,
    files: [
      ...backendOutput.emittedFiles,
      'index.d.ts',
      'package.json',
      'README.md',
    ],
  );
}

/// Dart build metadata (`1.0.0+3`) has no npm meaning and folding it into a
/// prerelease suffix would exclude the version from caret/tilde ranges:
/// strip it.
String _npmVersion(String dartVersion) => dartVersion.split('+').first;

String _readme(
  String npmName,
  TargetPackageInfo target,
  ApiModel api,
  String engineId, {
  required bool firestoreTypes,
}) {
  final buffer = StringBuffer()
    ..writeln('# $npmName')
    ..writeln()
    ..writeln(
      'TypeScript-ready build of the Dart package '
      '`${target.name}`, generated by '
      '[dart_typescript_builder](https://github.com/kekko7072/dart_typescript_builder) '
      '(engine: `$engineId`). Do not edit — regenerate from the Dart '
      'source instead.',
    )
    ..writeln()
    ..writeln('```ts')
    ..writeln("import { ${api.exportedNames.join(', ')} } from '$npmName';")
    ..writeln('```')
    ..writeln()
    ..writeln('## Boundary semantics')
    ..writeln()
    ..writeln(
      '- Dart `int`, `double` and `num` all arrive as JS `number` '
      '(IEEE-754 double); integers beyond 2^53 lose precision.',
    )
    ..writeln(
      '- Class instances are opaque handles over Dart objects: use '
      'the generated properties/methods, do not spread/clone them '
      '(JSON round trips destroy the handle).',
    )
    ..writeln(
      api.usesFirestoreTimestamp
          ? '- Dart `DateTime` crosses as a Firestore `Timestamp` '
                '(`firebase-admin` is a peer dependency — install it next '
                'to this package); the Dart local/UTC flag is not preserved '
                '(arrives as UTC).'
          : '- Dart `DateTime` crosses as a JS `Date` via epoch '
                'milliseconds (microseconds truncated); the Dart local/UTC '
                'flag is not preserved (arrives as UTC).',
    )
    ..writeln(
      '- `unknown` values (Dart `dynamic`) are deep-converted snapshots: '
      'mutations do not travel across the boundary; send changes back via '
      'return values.',
    );
  if (firestoreTypes) {
    buffer.writeln(
      '- Built with `--firestore-types`: inside `unknown` data, '
      '`Buffer`/`Uint8Array` crosses as Dart `Uint8List` (copied, returns '
      'as a fresh `Uint8Array`), and `GeoPoint`, `DocumentReference`, '
      '`FieldValue` and `VectorValue` pass through unchanged (identity '
      'preserved) — documents containing them survive round trips.',
    );
  }
  return buffer.toString();
}
