/// Stage 5 of the pipeline: assemble the installable npm package —
/// `package.json`, `index.d.ts`, a consumer README — around the runtime
/// files the compiler backend emitted.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'api_analyzer.dart';
import 'backend/compiler_backend.dart';
import 'dts_generator.dart';
import 'model.dart';

final class PackageResult {
  const PackageResult({required this.outputDir, required this.files});

  final String outputDir;

  /// File names relative to [outputDir].
  final List<String> files;
}

/// Writes `package.json`, `index.d.ts` and `README.md` into
/// [outputDir], merging the backend's required fields.
PackageResult writeNpmPackage({
  required String outputDir,
  required String npmName,
  required TargetPackageInfo target,
  required ApiModel api,
  required BackendOutput backendOutput,
  required String engineId,
}) {
  final dts = generateDts(api);
  File(p.join(outputDir, 'index.d.ts')).writeAsStringSync(dts);

  final packageJson = <String, Object?>{
    'name': npmName,
    'version': _npmVersion(target.version),
    'description':
        '${target.description ?? 'Compiled Dart package ${target.name}.'} '
        '(Compiled from Dart with dart_typescript_builder, engine: '
        '$engineId.)',
    'main': 'index.js',
    'types': 'index.d.ts',
    'exports': {
      '.': {'types': './index.d.ts', 'default': './index.js'},
    },
    'files': [...backendOutput.emittedFiles, 'index.d.ts', 'README.md'],
    ...backendOutput.packageJsonFields,
  };
  File(p.join(outputDir, 'package.json')).writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert(packageJson)}\n',
  );

  File(
    p.join(outputDir, 'README.md'),
  ).writeAsStringSync(_readme(npmName, target, api, engineId));

  return PackageResult(
    outputDir: outputDir,
    files: [
      ...backendOutput.emittedFiles,
      'index.d.ts',
      'package.json',
      'README.md',
    ],
  );
}

/// npm requires strict semver: Dart build metadata (`1.0.0+3`) is not valid
/// there — fold it into a prerelease-ish suffix.
String _npmVersion(String dartVersion) => dartVersion.replaceAll('+', '-');

String _readme(
  String npmName,
  TargetPackageInfo target,
  ApiModel api,
  String engineId,
) {
  final buffer = StringBuffer()
    ..writeln('# $npmName')
    ..writeln()
    ..writeln(
      'TypeScript-ready build of the Dart package '
      '`${target.name}`, generated by '
      '[dart_typescript_builder](https://github.com/kekko7072/dart_typescript_builder) '
      '(engine: `$engineId`). Do not edit — regenerate from the Dart '
      'source instead.',
    )
    ..writeln()
    ..writeln('```ts')
    ..writeln("import { ${api.exportedNames.join(', ')} } from '$npmName';")
    ..writeln('```')
    ..writeln()
    ..writeln('## Boundary semantics')
    ..writeln()
    ..writeln(
      '- Dart `int`, `double` and `num` all arrive as JS `number` '
      '(IEEE-754 double); integers beyond 2^53 lose precision.',
    )
    ..writeln(
      '- Class instances are opaque handles over Dart objects: use '
      'the generated properties/methods, do not spread/clone them.',
    );
  return buffer.toString();
}
