// Generated by dart_typescript_builder — do not edit.
// TypeScript declarations for the compiled Dart package
// `oop_logic` (package:oop_logic/oop_logic.dart).
//
// Boundary semantics:
// - Dart `int`, `double` and `num` all cross as JS `number`
//   (IEEE-754 double); integers beyond 2^53 lose precision.
// - Dart `DateTime` crosses as JS `Date` via epoch
//   milliseconds: microseconds are truncated and the Dart
//   local/UTC flag is not preserved (arrives in Dart as UTC).
// - `unknown` marks Dart `dynamic`/`Object`: only
//   JSON-compatible values survive the boundary.
// - Class instances are opaque handles over Dart objects;
//   only handles created by this package can be passed back.

/**
 * Enhanced enum: values still cross by name; members stay Dart-side.
 */
// Dart enum `Priority`: values cross by name;
// enhanced-enum members stay Dart-side.
export type Priority = "low" | "high";

/**
 * Traffic-light colors.
 */
// Dart enum `Signal`: values cross by name;
// enhanced-enum members stay Dart-side.
export type Signal = "red" | "amber" | "green";

/**
 * Returns an [Animal]-typed value whose runtime type is more derived:
 * the wrapper must expose the most-derived exported interface.
 */
export function adopt(kind: string, name: string): Animal;

/**
 * The next signal in the cycle.
 */
export function nextSignal(current: Signal): Signal;

/**
 * Nullable enums cross as `"..." | null`.
 */
export function parseSignal(name: string | null): Signal | null;

/**
 * Priorities of all given labels (enums inside collections).
 */
export function prioritize(flags: Record<string, boolean>): Priority[];

/**
 * Base of the hierarchy.
 */
export interface Animal {
  /**
   * The animal's name.
   */
  readonly name: string;
  /**
   * What it says.
   */
  speak(): string;
}

/**
 * A dog: `extends` in TypeScript, dispatched wrapper at runtime.
 */
export interface Dog extends Animal {
  readonly name: string;
  readonly tags: string[];
  speak(): string;
  /**
   * Dog-only API.
   */
  fetch(): string;
  /**
   * Adds a tag (mixin member, folded into the class interface).
   */
  tag(value: string): void;
}

/**
 * Creates a `Dog` (Dart constructor `Dog`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createDog(name: string): Dog;

/**
 * A kennel demonstrates supertype-typed collections.
 */
export interface Kennel {
  readonly residents: Animal[];
  admit(animal: Animal): void;
  /**
   * Everyone speaks (polymorphic dispatch on the Dart side).
   */
  chorus(): string[];
}

/**
 * Creates a `Kennel` (Dart constructor `Kennel`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createKennel(): Kennel;

/**
 * Deeper level of the hierarchy.
 */
export interface Puppy extends Dog {
  speak(): string;
}

/**
 * Creates a `Puppy` (Dart constructor `Puppy`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createPuppy(name: string): Puppy;
