// GENERATED BY dart_typescript_builder — DO NOT EDIT.
// dart:js_interop facade over package:hello_logic/hello_logic.dart.
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:hello_logic/hello_logic.dart' as $target;

@JS('Object.keys')
external JSArray<JSString> _objectKeys(JSObject object);

@JS('Object.defineProperty')
external void _definePropertyRaw(
  JSObject target,
  JSString name,
  JSObject descriptor,
);

@JS('Array.isArray')
external bool _isJsArray(JSAny? value);

@JS('Date')
extension type _JSDate._(JSObject _) implements JSObject {
  external _JSDate(int millisecondsSinceEpoch);
  external double getTime();
}

String _describe(JSAny? value) {
  if (value == null) return 'null';
  if (_isJsArray(value)) return 'an array';
  if (value.typeofEquals('string')) return 'a string';
  if (value.typeofEquals('number')) return 'a number';
  if (value.typeofEquals('boolean')) return 'a boolean';
  if (value.typeofEquals('function')) return 'a function';
  return 'a JS object';
}

// Injected by the package entry module. Boundary validation errors are
// thrown from a JS frame so they reach callers as real TypeErrors with a
// message — a Dart exception escaping a dart2wasm module surfaces as an
// opaque, message-less WebAssembly.Exception.
@JS('__dtb_throw__')
external JSFunction? get _jsThrower;

Never _throwBoundaryError(String message) {
  final thrower = _jsThrower;
  if (thrower != null) {
    thrower.callAsFunction(null, message.toJS);
  }
  throw ArgumentError(message);
}

Never _fail(String expected, JSAny? value) =>
    _throwBoundaryError('expected $expected, got ${_describe(value)}');

void _defineGetter(JSObject target, String name, JSFunction getter) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

void _defineAccessor(
  JSObject target,
  String name,
  JSFunction getter,
  JSFunction setter,
) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['set'] = setter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

JSObject? _asOptions(JSAny? value, String owner) {
  if (value == null) return null;
  if (value.isA<JSObject>() && !_isJsArray(value)) return value as JSObject;
  _throwBoundaryError(
    "expected an options object for '$owner', got ${_describe(value)}",
  );
}

// Own-property check: `has`/`in` walks the prototype chain, which would make
// options named after Object.prototype members (toString, constructor, ...)
// always look "present".
@JS('Object.hasOwn')
external bool _hasOwn(JSObject object, JSString name);

JSAny? _requireOption(JSObject? options, String name, String owner) {
  if (options == null || !_hasOwn(options, name.toJS)) {
    _throwBoundaryError("missing required option '$name' of '$owner'");
  }
  return options[name];
}

JSAny? _readOption(JSObject? options, String name) =>
    (options == null || !_hasOwn(options, name.toJS)) ? null : options[name];

/// Sets a map entry on an outgoing plain object. A key literally named
/// `__proto__` must go through defineProperty: plain assignment would
/// replace the object's prototype instead of storing the entry.
void _setEntry(JSObject target, String key, JSAny? value) {
  if (key == '__proto__') {
    final descriptor = JSObject();
    descriptor['value'] = value;
    descriptor['enumerable'] = true.toJS;
    descriptor['writable'] = true.toJS;
    descriptor['configurable'] = true.toJS;
    _definePropertyRaw(target, key.toJS, descriptor);
  } else {
    target[key] = value;
  }
}

/// Outgoing streams: a JS object implementing the async-iteration protocol.
/// `for await` works; an early `break` (protocol `return`) cancels the Dart
/// subscription.
JSObject _streamToJs<T>(Stream<T> stream, JSAny? Function(T) convert) {
  final iterable = JSObject();
  iterable.setProperty(JSSymbol.asyncIterator, (() {
    final iterator = StreamIterator<T>(stream);
    final jsIterator = JSObject();
    jsIterator['next'] = (() {
      return iterator.moveNext().then<JSAny?>((hasNext) {
        final result = JSObject();
        result['done'] = (!hasNext).toJS;
        result['value'] = hasNext ? convert(iterator.current) : null;
        return result;
      }).toJS;
    }).toJS;
    jsIterator['return'] = (([JSAny? value]) {
      final result = JSObject();
      result['done'] = true.toJS;
      unawaited(iterator.cancel());
      return result;
    }).toJS;
    return jsIterator;
  }).toJS);
  return iterable;
}

/// Incoming async iterables, pulled into a Dart stream.
Stream<T> _streamFromJs<T>(JSAny? value, T Function(JSAny?) convert) async* {
  final iterable = value as JSObject;
  final makeIterator = iterable.getProperty<JSFunction>(
    JSSymbol.asyncIterator,
  );
  final iterator = makeIterator.callAsFunction(iterable) as JSObject;
  final next = iterator.getProperty<JSFunction>('next'.toJS);
  while (true) {
    final result =
        await (next.callAsFunction(iterator) as JSPromise<JSAny?>).toDart
            as JSObject;
    if ((result['done'] as JSBoolean?)?.toDart ?? false) break;
    yield convert(result['value']);
  }
}

/// Builds a FRESH JS array. Never use `List.toJS` for outgoing values: on
/// dart2js it is a zero-copy cast and the Dart list's internal `$ti`
/// type-info symbol would leak into consumer-visible arrays.
JSArray<JSAny?> _jsArrayOf(Iterable<JSAny?> items) {
  final result = JSArray<JSAny?>();
  var index = 0;
  for (final item in items) {
    result.setProperty((index++).toJS, item);
  }
  return result;
}

JSAny? _dateTimeToJs(DateTime value) => _JSDate(value.millisecondsSinceEpoch);

bool _isJsDateTimeValue(JSAny? value) =>
    value != null && value.instanceOfString('Date');

DateTime _dateTimeFromJs(JSAny? value) {
  if (value != null && value.instanceOfString('Date')) {
    final milliseconds = (value as _JSDate).getTime();
    if (!milliseconds.isNaN) {
      return DateTime.fromMillisecondsSinceEpoch(
        milliseconds.toInt(),
        isUtc: true,
      );
    }
  }
  _fail('a JS Date', value);
}

JSAny? _dynamicToJs(Object? value) =>
    _dynamicToJsRec(value, Set<Object>.identity());

JSAny? _dynamicToJsRec(Object? value, Set<Object> seen) {
  if (value == null) return null;
  if (value is bool) return value.toJS;
  if (value is num) return value.toJS;
  if (value is String) return value.toJS;
  if (value is DateTime) return _dateTimeToJs(value);
  if (value is $target.Counter) return _wrap_Counter(value);
  if (value is Enum) {
    _throwBoundaryError(
      'enum values cannot cross inside dynamic data '
      '(${value.runtimeType}); use a typed API',
    );
  }
  if (value is Map) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = JSObject();
    value.forEach((key, item) {
      if (key is! String) {
        _throwBoundaryError(
          'only String map keys cross the boundary, '
          'got a key of type ${key.runtimeType}',
        );
      }
      _setEntry(result, key, _dynamicToJsRec(item, seen));
    });
    seen.remove(value);
    return result;
  }
  if (value is Iterable) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = _jsArrayOf(value.map((item) => _dynamicToJsRec(item, seen)));
    seen.remove(value);
    return result;
  }
  _throwBoundaryError(
    'cannot marshal a value of type ${value.runtimeType} across the '
    'boundary',
  );
}

Object? _dynamicFromJs(JSAny? value) {
  if (value == null) return null;
  if (value.typeofEquals('boolean')) return (value as JSBoolean).toDart;
  if (value.typeofEquals('number')) {
    final number = (value as JSNumber).toDartDouble;
    // Whole numbers become int, matching dart2js/web semantics on both
    // engines (2^53 guards against precision-lossy conversions).
    return (number.isFinite &&
            number.truncateToDouble() == number &&
            number.abs() <= 9007199254740992)
        ? number.toInt()
        : number;
  }
  if (value.typeofEquals('string')) return (value as JSString).toDart;
  if (_isJsArray(value)) {
    return [
      for (final item in (value as JSArray<JSAny?>).toDart)
        _dynamicFromJs(item),
    ];
  }
  if (_isJsDateTimeValue(value)) return _dateTimeFromJs(value);
  if (value.typeofEquals('function')) {
    _fail('a marshallable value (functions cannot cross the boundary)', value);
  }
  if (value.isA<JSObject>()) {
    final object = value as JSObject;
    final handle = object['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      return (handle as JSBoxedDartObject).toDart;
    }
    return <String, dynamic>{
      for (final key in _objectKeys(object).toDart.map((k) => k.toDart))
        key: _dynamicFromJs(object[key]),
    };
  }
  _fail('a marshallable value', value);
}

final Expando<JSObject> _wrapCache_Counter = Expando();

/// Opaque JS handle over `Counter` (identity-cached).
JSObject _wrap_Counter($target.Counter inner) {
  final cached = _wrapCache_Counter[inner];
  if (cached != null) return cached;
  final wrapper = JSObject();
  _wrapCache_Counter[inner] = wrapper;
  wrapper['__dtb_handle__'] = inner.toJSBox;
  _defineGetter(wrapper, 'label', (() => inner.label.toJS).toJS);
  _defineAccessor(
    wrapper,
    'count',
    (() => inner.count.toJS).toJS,
    ((JSAny? value) {
      inner.count = _toDartInt(value);
    }).toJS,
  );
  wrapper['increment'] = (([JSAny? $a0]) {
    return inner.increment(_toDartInt($a0)).toJS;
  }).toJS;
  wrapper['describe'] = (() {
    return inner.describe().toJS;
  }).toJS;
  wrapper['clear'] = (() {
    inner.clear();
  }).toJS;
  return wrapper;
}

$target.Counter _unwrap_Counter(JSAny? value) {
  if (value != null && value.isA<JSObject>()) {
    final handle = (value as JSObject)['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      final inner = (handle as JSBoxedDartObject).toDart;
      if (inner is $target.Counter) return inner;
    }
  }
  _fail('a Counter handle created by this package', value);
}

int _toDartInt(JSAny? value) {
  if (value == null || !value.typeofEquals('number')) {
    _fail('a number', value);
  }
  final number = (value as JSNumber).toDartDouble;
  if (!number.isFinite ||
      number.truncateToDouble() != number ||
      number.abs() > 9007199254740992) {
    _fail('a safe integer (|n| <= 2^53)', value);
  }
  return number.toInt();
}

num _toDartNum(JSAny? value) {
  if (value == null || !value.typeofEquals('number')) {
    _fail('a number', value);
  }
  final number = (value as JSNumber).toDartDouble;
  return (number.isFinite &&
          number.truncateToDouble() == number &&
          number.abs() <= 9007199254740992)
      ? number.toInt()
      : number;
}

String _toDartString(JSAny? value) =>
    value != null && value.typeofEquals('string')
    ? (value as JSString).toDart
    : _fail('a string', value);

void _install(JSObject target) {
  target['add'] = (([JSAny? $a0, JSAny? $a1]) {
    return $target.add(_toDartInt($a0), _toDartInt($a1)).toJS;
  }).toJS;
  target['greet'] = (([JSAny? $a0]) {
    return $target.greet(_toDartString($a0)).toJS;
  }).toJS;
  target['half'] = (([JSAny? $a0]) {
    return $target.half(_toDartNum($a0)).toJS;
  }).toJS;
  target['isEven'] = (([JSAny? $a0]) {
    return $target.isEven(_toDartInt($a0)).toJS;
  }).toJS;
  target['createCounter'] = (([JSAny? $a0, JSAny? $a1]) {
    return _wrap_Counter($target.Counter(_toDartString($a0), _toDartInt($a1)));
  }).toJS;
}

void main() {
  final exports = JSObject();
  _install(exports);
  // Node CommonJS: node_preamble exposes `module.exports` as
  // `self.exports`; installing there makes the compiled file
  // a require()-able module.
  final moduleExports = globalContext['exports'];
  if (moduleExports != null && moduleExports.isA<JSObject>()) {
    _install(moduleExports as JSObject);
  }
  // WASM / browser fallback: a well-known global key.
  globalContext['__dtb_exports_hello_logic__'] = exports;
}
