// GENERATED BY dart_typescript_builder — DO NOT EDIT.
// dart:js_interop facade over package:hello_logic/hello_logic.dart.
// ignore_for_file: type=lint

import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:hello_logic/hello_logic.dart' as $target;

/// JS-facing wrapper for `Counter` — an opaque
/// handle exposing the class through generated accessors.
@JSExport()
final class _$CounterExport {
  _$CounterExport(this._inner);

  final $target.Counter _inner;

  String get label => _inner.label;

  int get count => _inner.count;
  set count(int value) {
    _inner.count = value;
  }

  int increment(int by) => _inner.increment(by);

  String describe() => _inner.describe();

  void clear() => _inner.clear();
}

void _install(JSObject target) {
  target['add'] = ((int a, int b) => $target.add(a, b)).toJS;
  target['greet'] = ((String name) => $target.greet(name)).toJS;
  target['half'] = ((num value) => $target.half(value)).toJS;
  target['isEven'] = ((int value) => $target.isEven(value)).toJS;
  target['createCounter'] = ((String label, int count) => createJSInteropWrapper(_$CounterExport($target.Counter(label, count)))).toJS;
}

void main() {
  final exports = JSObject();
  _install(exports);
  // Node CommonJS: node_preamble exposes `module.exports` as
  // `self.exports`; installing there makes the compiled file
  // a require()-able module.
  final moduleExports = globalContext['exports'];
  if (moduleExports != null && moduleExports.isA<JSObject>()) {
    _install(moduleExports as JSObject);
  }
  // WASM / browser fallback: a well-known global key.
  globalContext['__dtb_exports_hello_logic__'] = exports;
}
