// Generated by dart_typescript_builder — do not edit.
// TypeScript declarations for the compiled Dart package
// `hello_logic` (package:hello_logic/hello_logic.dart).
//
// Boundary semantics:
// - Dart `int`, `double` and `num` all cross as JS `number`
//   (IEEE-754 double); integers beyond 2^53 lose precision.
// - Dart `DateTime` crosses as JS `Date` via epoch
//   milliseconds: microseconds are truncated and the Dart
//   local/UTC flag is not preserved (arrives in Dart as UTC).
// - `unknown` marks Dart `dynamic`/`Object`: only
//   JSON-compatible values survive the boundary.
// - Class instances are opaque handles over Dart objects;
//   only handles created by this package can be passed back.

/**
 * Adds two integers.
 */
export function add(a: number, b: number): number;

/**
 * Greets [name].
 */
export function greet(name: string): string;

/**
 * Returns half of [value].
 */
export function half(value: number): number;

/**
 * Whether [value] is even.
 */
export function isEven(value: number): boolean;

/**
 * A labelled counter.
 */
export interface Counter {
  /**
   * Display label for this counter.
   */
  readonly label: string;
  /**
   * Current count. Mutable from JS.
   */
  count: number;
  /**
   * Increments by [by] and returns the new count.
   */
  increment(by: number): number;
  /**
   * Human-readable state.
   */
  describe(): string;
  /**
   * Resets the count to zero.
   */
  clear(): void;
}

/**
 * Creates a `Counter` (Dart constructor `Counter`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createCounter(label: string, count: number): Counter;
