// GENERATED BY dart_typescript_builder — DO NOT EDIT.
// dart:js_interop facade over package:boundary_logic/boundary_logic.dart.
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';

import 'package:boundary_logic/boundary_logic.dart' as $target;

@JS('Object.keys')
external JSArray<JSString> _objectKeys(JSObject object);

@JS('Object.defineProperty')
external void _definePropertyRaw(
  JSObject target,
  JSString name,
  JSObject descriptor,
);

@JS('Array.isArray')
external bool _isJsArray(JSAny? value);

@JS('Date')
extension type _JSDate._(JSObject _) implements JSObject {
  external _JSDate(int millisecondsSinceEpoch);
  external double getTime();
}

String _describe(JSAny? value) {
  if (value == null) return 'null';
  if (_isJsArray(value)) return 'an array';
  if (value.typeofEquals('string')) return 'a string';
  if (value.typeofEquals('number')) return 'a number';
  if (value.typeofEquals('boolean')) return 'a boolean';
  if (value.typeofEquals('function')) return 'a function';
  return 'a JS object';
}

// Injected by the package entry module. Boundary validation errors are
// thrown from a JS frame so they reach callers as real TypeErrors with a
// message — a Dart exception escaping a dart2wasm module surfaces as an
// opaque, message-less WebAssembly.Exception.
@JS('__dtb_throw__')
external JSFunction? get _jsThrower;

Never _throwBoundaryError(String message) {
  final thrower = _jsThrower;
  if (thrower != null) {
    thrower.callAsFunction(null, message.toJS);
  }
  throw ArgumentError(message);
}

Never _fail(String expected, JSAny? value) =>
    _throwBoundaryError('expected $expected, got ${_describe(value)}');

void _defineGetter(JSObject target, String name, JSFunction getter) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

void _defineAccessor(
  JSObject target,
  String name,
  JSFunction getter,
  JSFunction setter,
) {
  final descriptor = JSObject();
  descriptor['get'] = getter;
  descriptor['set'] = setter;
  descriptor['enumerable'] = true.toJS;
  descriptor['configurable'] = true.toJS;
  _definePropertyRaw(target, name.toJS, descriptor);
}

JSObject? _asOptions(JSAny? value, String owner) {
  if (value == null) return null;
  if (value.isA<JSObject>() && !_isJsArray(value)) return value as JSObject;
  _throwBoundaryError(
    "expected an options object for '$owner', got ${_describe(value)}",
  );
}

// Own-property check: `has`/`in` walks the prototype chain, which would make
// options named after Object.prototype members (toString, constructor, ...)
// always look "present".
@JS('Object.hasOwn')
external bool _hasOwn(JSObject object, JSString name);

JSAny? _requireOption(JSObject? options, String name, String owner) {
  if (options == null || !_hasOwn(options, name.toJS)) {
    _throwBoundaryError("missing required option '$name' of '$owner'");
  }
  return options[name];
}

JSAny? _readOption(JSObject? options, String name) =>
    (options == null || !_hasOwn(options, name.toJS)) ? null : options[name];

/// Sets a map entry on an outgoing plain object. A key literally named
/// `__proto__` must go through defineProperty: plain assignment would
/// replace the object's prototype instead of storing the entry.
void _setEntry(JSObject target, String key, JSAny? value) {
  if (key == '__proto__') {
    final descriptor = JSObject();
    descriptor['value'] = value;
    descriptor['enumerable'] = true.toJS;
    descriptor['writable'] = true.toJS;
    descriptor['configurable'] = true.toJS;
    _definePropertyRaw(target, key.toJS, descriptor);
  } else {
    target[key] = value;
  }
}

/// Outgoing streams: a JS object implementing the async-iteration protocol.
/// `for await` works; an early `break` (protocol `return`) cancels the Dart
/// subscription.
JSObject _streamToJs<T>(Stream<T> stream, JSAny? Function(T) convert) {
  final iterable = JSObject();
  iterable.setProperty(JSSymbol.asyncIterator, (() {
    final iterator = StreamIterator<T>(stream);
    final jsIterator = JSObject();
    jsIterator['next'] = (() {
      return iterator.moveNext().then<JSAny?>((hasNext) {
        final result = JSObject();
        result['done'] = (!hasNext).toJS;
        result['value'] = hasNext ? convert(iterator.current) : null;
        return result;
      }).toJS;
    }).toJS;
    jsIterator['return'] = (([JSAny? value]) {
      final result = JSObject();
      result['done'] = true.toJS;
      unawaited(iterator.cancel());
      return result;
    }).toJS;
    return jsIterator;
  }).toJS);
  return iterable;
}

/// Incoming async iterables, pulled into a Dart stream.
Stream<T> _streamFromJs<T>(JSAny? value, T Function(JSAny?) convert) async* {
  final iterable = value as JSObject;
  final makeIterator = iterable.getProperty<JSFunction>(
    JSSymbol.asyncIterator,
  );
  final iterator = makeIterator.callAsFunction(iterable) as JSObject;
  final next = iterator.getProperty<JSFunction>('next'.toJS);
  while (true) {
    final result =
        await (next.callAsFunction(iterator) as JSPromise<JSAny?>).toDart
            as JSObject;
    if ((result['done'] as JSBoolean?)?.toDart ?? false) break;
    yield convert(result['value']);
  }
}

/// Builds a FRESH JS array. Never use `List.toJS` for outgoing values: on
/// dart2js it is a zero-copy cast and the Dart list's internal `$ti`
/// type-info symbol would leak into consumer-visible arrays.
JSArray<JSAny?> _jsArrayOf(Iterable<JSAny?> items) {
  final result = JSArray<JSAny?>();
  var index = 0;
  for (final item in items) {
    result.setProperty((index++).toJS, item);
  }
  return result;
}

// Injected by the package entry module (index.js) from
// firebase-admin/firestore before the Dart program initializes.
@JS('__dtb_Timestamp__')
external JSAny? get _timestampClass;

@JS('__dtb_Timestamp__')
extension type _FsTimestamp._(JSObject _) implements JSObject {
  external _FsTimestamp(int seconds, int nanoseconds);
  external int get seconds;
  external int get nanoseconds;
}

bool _isFsTimestamp(JSAny? value) {
  if (value == null || !value.isA<JSObject>()) return false;
  final timestampClass = _timestampClass;
  if (timestampClass != null &&
      timestampClass.isA<JSFunction>() &&
      value.instanceof(timestampClass as JSFunction)) {
    return true;
  }
  // A Timestamp from a different firebase-admin copy: duck-check the
  // Timestamp contract instead of the identity of the class.
  final object = value as JSObject;
  return object.has('seconds') &&
      object.has('nanoseconds') &&
      object.has('toMillis');
}

bool _isJsDateTimeValue(JSAny? value) =>
    _isFsTimestamp(value) ||
    (value != null && value.instanceOfString('Date'));

JSAny? _dateTimeToJs(DateTime value) {
  if (_timestampClass == null) {
    _throwBoundaryError(
      'firebase-admin Timestamp is not available: load this package through '
      'its entry module (index.js), which injects it.',
    );
  }
  final microseconds = value.microsecondsSinceEpoch;
  var seconds = microseconds ~/ 1000000;
  var remainder = microseconds - seconds * 1000000;
  if (remainder < 0) {
    seconds -= 1;
    remainder += 1000000;
  }
  return _FsTimestamp(seconds, remainder * 1000);
}

DateTime _dateTimeFromJs(JSAny? value) {
  if (_isFsTimestamp(value)) {
    final timestamp = value as _FsTimestamp;
    return DateTime.fromMicrosecondsSinceEpoch(
      timestamp.seconds * 1000000 + timestamp.nanoseconds ~/ 1000,
      isUtc: true,
    );
  }
  // Graceful: accept a plain JS Date where a Timestamp is expected.
  if (value != null && value.instanceOfString('Date')) {
    final milliseconds = (value as _JSDate).getTime();
    if (!milliseconds.isNaN) {
      return DateTime.fromMillisecondsSinceEpoch(
        milliseconds.toInt(),
        isUtc: true,
      );
    }
  }
  _fail('a Firestore Timestamp', value);
}

JSAny? _dynamicToJs(Object? value) =>
    _dynamicToJsRec(value, Set<Object>.identity());

JSAny? _dynamicToJsRec(Object? value, Set<Object> seen) {
  if (value == null) return null;
  if (value is bool) return value.toJS;
  if (value is num) return value.toJS;
  if (value is String) return value.toJS;
  if (value is DateTime) return _dateTimeToJs(value);
  if (value is $target.Note) return _wrap_Note(value);
  if (value is $target.NoteRepository) return _wrap_NoteRepository(value);
  if (value is $target.Notebook) return _wrap_Notebook(value);
  if (value is Enum) {
    _throwBoundaryError(
      'enum values cannot cross inside dynamic data '
      '(${value.runtimeType}); use a typed API',
    );
  }
  if (value is Map) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = JSObject();
    value.forEach((key, item) {
      if (key is! String) {
        _throwBoundaryError(
          'only String map keys cross the boundary, '
          'got a key of type ${key.runtimeType}',
        );
      }
      _setEntry(result, key, _dynamicToJsRec(item, seen));
    });
    seen.remove(value);
    return result;
  }
  if (value is Iterable) {
    if (!seen.add(value)) {
      _throwBoundaryError('cyclic data cannot cross the boundary');
    }
    final result = _jsArrayOf(value.map((item) => _dynamicToJsRec(item, seen)));
    seen.remove(value);
    return result;
  }
  _throwBoundaryError(
    'cannot marshal a value of type ${value.runtimeType} across the '
    'boundary',
  );
}

Object? _dynamicFromJs(JSAny? value) {
  if (value == null) return null;
  if (value.typeofEquals('boolean')) return (value as JSBoolean).toDart;
  if (value.typeofEquals('number')) {
    final number = (value as JSNumber).toDartDouble;
    // Whole numbers become int, matching dart2js/web semantics on both
    // engines (2^53 guards against precision-lossy conversions).
    return (number.isFinite &&
            number.truncateToDouble() == number &&
            number.abs() <= 9007199254740992)
        ? number.toInt()
        : number;
  }
  if (value.typeofEquals('string')) return (value as JSString).toDart;
  if (_isJsArray(value)) {
    return [
      for (final item in (value as JSArray<JSAny?>).toDart)
        _dynamicFromJs(item),
    ];
  }
  if (_isJsDateTimeValue(value)) return _dateTimeFromJs(value);
  if (value.typeofEquals('function')) {
    _fail('a marshallable value (functions cannot cross the boundary)', value);
  }
  if (value.isA<JSObject>()) {
    final object = value as JSObject;
    final handle = object['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      return (handle as JSBoxedDartObject).toDart;
    }
    return <String, dynamic>{
      for (final key in _objectKeys(object).toDart.map((k) => k.toDart))
        key: _dynamicFromJs(object[key]),
    };
  }
  _fail('a marshallable value', value);
}

final Expando<JSObject> _wrapCache_Note = Expando();

/// Opaque JS handle over `Note` (identity-cached).
JSObject _wrap_Note($target.Note inner) {
  final cached = _wrapCache_Note[inner];
  if (cached != null) return cached;
  final wrapper = JSObject();
  _wrapCache_Note[inner] = wrapper;
  wrapper['__dtb_handle__'] = inner.toJSBox;
  _defineAccessor(
    wrapper,
    'title',
    (() => inner.title.toJS).toJS,
    ((JSAny? value) {
      inner.title = _toDartString(value);
    }).toJS,
  );
  _defineGetter(wrapper, 'createdAt', (() => _dateTimeToJs(inner.createdAt)).toJS);
  _defineGetter(wrapper, 'tags', (() => _toJsListOfString(inner.tags)).toJS);
  _defineAccessor(
    wrapper,
    'meta',
    (() => _toJsMapOfDyn(inner.meta)).toJS,
    ((JSAny? value) {
      inner.meta = _toDartMapOfDyn(value);
    }).toJS,
  );
  wrapper['tag'] = (([JSAny? $a0]) {
    return _wrap_Note(inner.tag(_toDartString($a0)));
  }).toJS;
  wrapper['toMap'] = (() {
    return _toJsMapOfDyn(inner.toMap());
  }).toJS;
  return wrapper;
}

$target.Note _unwrap_Note(JSAny? value) {
  if (value != null && value.isA<JSObject>()) {
    final handle = (value as JSObject)['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      final inner = (handle as JSBoxedDartObject).toDart;
      if (inner is $target.Note) return inner;
    }
  }
  _fail('a Note handle created by this package', value);
}

final Expando<JSObject> _wrapCache_NoteRepository = Expando();

/// Opaque JS handle over `NoteRepository` (identity-cached).
JSObject _wrap_NoteRepository($target.NoteRepository inner) {
  final cached = _wrapCache_NoteRepository[inner];
  if (cached != null) return cached;
  final wrapper = JSObject();
  _wrapCache_NoteRepository[inner] = wrapper;
  wrapper['__dtb_handle__'] = inner.toJSBox;
  wrapper['getByTitle'] = (([JSAny? $a0]) {
    return _toJsFutureOfNRefNote(inner.getByTitle(_toDartString($a0)));
  }).toJS;
  wrapper['watchAll'] = (() {
    return _toJsStreamOfListOfRefNote(inner.watchAll());
  }).toJS;
  wrapper['save'] = (([JSAny? $options]) {
    final $opts = _asOptions($options, 'NoteRepository.save');
    return _toJsFutureOfVoid(inner.save(note: _unwrap_Note(_requireOption($opts, 'note', 'NoteRepository.save')), overwrite: _toDartBool(_requireOption($opts, 'overwrite', 'NoteRepository.save'))));
  }).toJS;
  return wrapper;
}

$target.NoteRepository _unwrap_NoteRepository(JSAny? value) {
  if (value != null && value.isA<JSObject>()) {
    final handle = (value as JSObject)['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      final inner = (handle as JSBoxedDartObject).toDart;
      if (inner is $target.NoteRepository) return inner;
    }
  }
  _fail('a NoteRepository handle created by this package', value);
}

final Expando<JSObject> _wrapCache_Notebook = Expando();

/// Opaque JS handle over `Notebook` (identity-cached).
JSObject _wrap_Notebook($target.Notebook inner) {
  final cached = _wrapCache_Notebook[inner];
  if (cached != null) return cached;
  final wrapper = JSObject();
  _wrapCache_Notebook[inner] = wrapper;
  wrapper['__dtb_handle__'] = inner.toJSBox;
  _defineGetter(wrapper, 'name', (() => inner.name.toJS).toJS);
  _defineGetter(wrapper, 'notes', (() => _toJsListOfRefNote(inner.notes)).toJS);
  wrapper['add'] = (([JSAny? $a0]) {
    inner.add(_unwrap_Note($a0));
  }).toJS;
  wrapper['find'] = (([JSAny? $a0]) {
    return _toJsNRefNote(inner.find(_toDartString($a0)));
  }).toJS;
  wrapper['all'] = (() {
    return _toJsListOfRefNote(inner.all());
  }).toJS;
  wrapper['load'] = (() {
    return _toJsFutureOfListOfRefNote(inner.load());
  }).toJS;
  return wrapper;
}

$target.Notebook _unwrap_Notebook(JSAny? value) {
  if (value != null && value.isA<JSObject>()) {
    final handle = (value as JSObject)['__dtb_handle__'];
    if (handle != null && handle.isA<JSBoxedDartObject>()) {
      final inner = (handle as JSBoxedDartObject).toDart;
      if (inner is $target.Notebook) return inner;
    }
  }
  _fail('a Notebook handle created by this package', value);
}

bool _toDartBool(JSAny? value) =>
    value != null && value.typeofEquals('boolean')
    ? (value as JSBoolean).toDart
    : _fail('a boolean', value);

Future<int> _toDartFutureOfInt(JSAny? value) {
  if (value == null || !value.isA<JSPromise>()) {
    _fail('a Promise', value);
  }
  return (value as JSPromise<JSAny?>)
      .toDart
      .then((result) => _toDartInt(result));
}

int _toDartInt(JSAny? value) {
  if (value == null || !value.typeofEquals('number')) {
    _fail('a number', value);
  }
  final number = (value as JSNumber).toDartDouble;
  if (!number.isFinite ||
      number.truncateToDouble() != number ||
      number.abs() > 9007199254740992) {
    _fail('a safe integer (|n| <= 2^53)', value);
  }
  return number.toInt();
}

List<int> _toDartListOfInt(JSAny? value) {
  if (value == null || !_isJsArray(value)) {
    _fail('an array', value);
  }
  return [
    for (final item in (value as JSArray<JSAny?>).toDart)
      _toDartInt(item),
  ];
}

List<Map<String, dynamic>> _toDartListOfMapOfDyn(JSAny? value) {
  if (value == null || !_isJsArray(value)) {
    _fail('an array', value);
  }
  return [
    for (final item in (value as JSArray<JSAny?>).toDart)
      _toDartMapOfDyn(item),
  ];
}

List<String?> _toDartListOfNString(JSAny? value) {
  if (value == null || !_isJsArray(value)) {
    _fail('an array', value);
  }
  return [
    for (final item in (value as JSArray<JSAny?>).toDart)
      _toDartNString(item),
  ];
}

List<String> _toDartListOfString(JSAny? value) {
  if (value == null || !_isJsArray(value)) {
    _fail('an array', value);
  }
  return [
    for (final item in (value as JSArray<JSAny?>).toDart)
      _toDartString(item),
  ];
}

Map<String, dynamic> _toDartMapOfDyn(JSAny? value) {
  if (value == null || !value.isA<JSObject>() || _isJsArray(value)) {
    _fail('a plain object', value);
  }
  final object = value as JSObject;
  return {
    for (final key in _objectKeys(object).toDart.map((k) => k.toDart))
      key: _dynamicFromJs(object[key]),
  };
}

List<String>? _toDartNListOfString(JSAny? value) =>
    value == null ? null : _toDartListOfString(value);

String? _toDartNString(JSAny? value) =>
    value == null ? null : _toDartString(value);

String _toDartString(JSAny? value) =>
    value != null && value.typeofEquals('string')
    ? (value as JSString).toDart
    : _fail('a string', value);

JSAny? _toJsFutureOfInt(Future<int> value) =>
    value.then<JSAny?>((result) => result.toJS).toJS;

JSAny? _toJsFutureOfListOfRefNote(Future<List<$target.Note>> value) =>
    value.then<JSAny?>((result) => _toJsListOfRefNote(result)).toJS;

JSAny? _toJsFutureOfNRefNote(Future<$target.Note?> value) =>
    value.then<JSAny?>((result) => _toJsNRefNote(result)).toJS;

JSAny? _toJsFutureOfString(Future<String> value) =>
    value.then<JSAny?>((result) => result.toJS).toJS;

JSAny? _toJsFutureOfVoid(Future<void> value) => value.toJS;

JSAny? _toJsListOfNString(Iterable<String?> value) =>
    _jsArrayOf(value.map((item) => item?.toJS));

JSAny? _toJsListOfRefNote(Iterable<$target.Note> value) =>
    _jsArrayOf(value.map((item) => _wrap_Note(item)));

JSAny? _toJsListOfString(Iterable<String> value) =>
    _jsArrayOf(value.map((item) => item.toJS));

JSAny? _toJsMapOfDyn(Map<String, dynamic> value) {
  final result = JSObject();
  value.forEach((key, item) {
    _setEntry(result, key, _dynamicToJs(item));
  });
  return result;
}

JSAny? _toJsMapOfInt(Map<String, int> value) {
  final result = JSObject();
  value.forEach((key, item) {
    _setEntry(result, key, item.toJS);
  });
  return result;
}

JSAny? _toJsNRefNote($target.Note? value) =>
    value == null ? null : _wrap_Note(value);

JSAny? _toJsStreamOfListOfRefNote(Stream<List<$target.Note>> value) =>
    _streamToJs<List<$target.Note>>(
      value,
      (item) => _toJsListOfRefNote(item),
    );

void _install(JSObject target) {
  target['kDefaultLimit'] = $target.kDefaultLimit.toJS;
  target['kLocales'] = _toJsListOfString($target.kLocales);
  target['addDays'] = (([JSAny? $a0, JSAny? $a1]) {
    return _dateTimeToJs($target.addDays(_dateTimeFromJs($a0), _toDartInt($a1)));
  }).toJS;
  target['annotate'] = (([JSAny? $a0]) {
    return _dynamicToJs($target.annotate(_dynamicFromJs($a0)));
  }).toJS;
  target['delayedGreet'] = (([JSAny? $a0, JSAny? $a1]) {
    return _toJsFutureOfString($target.delayedGreet(_toDartString($a0), _toDartInt($a1)));
  }).toJS;
  target['doubleEventually'] = (([JSAny? $a0]) {
    return _toJsFutureOfInt($target.doubleEventually(_toDartFutureOfInt($a0)));
  }).toJS;
  target['lengths'] = (([JSAny? $a0]) {
    return _toJsMapOfInt($target.lengths(_toDartListOfString($a0)));
  }).toJS;
  target['maybeLength'] = (([JSAny? $a0]) {
    return $target.maybeLength(_toDartNString($a0))?.toJS;
  }).toJS;
  target['pad'] = (([JSAny? $a0, JSAny? $options]) {
    final $opts = _asOptions($options, 'pad');
    final JSAny? $o1Raw = _readOption($opts, 'fill');
    final String $o1 = $o1Raw == null
        ? '.'
        : _toDartString($o1Raw);
    return $target.pad(_toDartString($a0), width: _toDartInt(_requireOption($opts, 'width', 'pad')), fill: $o1).toJS;
  }).toJS;
  target['repeat'] = (([JSAny? $a0, JSAny? $a1]) {
    final JSAny? $p1Raw = $a1;
    final int $p1 = $p1Raw == null
        ? 2
        : _toDartInt($p1Raw);
    return $target.repeat(_toDartString($a0), $p1).toJS;
  }).toJS;
  target['shout'] = (([JSAny? $a0]) {
    return _toJsListOfNString($target.shout(_toDartListOfNString($a0)));
  }).toJS;
  target['sum'] = (([JSAny? $a0]) {
    return $target.sum(_toDartListOfInt($a0)).toJS;
  }).toJS;
  target['createNote'] = (([JSAny? $a0, JSAny? $options]) {
    final $opts = _asOptions($options, 'createNote');
    return _wrap_Note($target.Note(_toDartString($a0), createdAt: _dateTimeFromJs(_requireOption($opts, 'createdAt', 'createNote')), tags: _toDartNListOfString(_readOption($opts, 'tags'))));
  }).toJS;
  {
    final namespace = JSObject();
    _defineGetter(namespace, 'template', (() => _toJsMapOfDyn($target.Note.template)).toJS);
    namespace['fromMap'] = (([JSAny? $a0]) {
    return _wrap_Note($target.Note.fromMap(_toDartMapOfDyn($a0)));
  }).toJS;
    namespace['listFromMaps'] = (([JSAny? $a0]) {
    return _toJsListOfRefNote($target.Note.listFromMaps(_toDartListOfMapOfDyn($a0)));
  }).toJS;
    target['Note'] = namespace;
  }
  target['createNotebook'] = (([JSAny? $a0]) {
    return _wrap_Notebook($target.Notebook(_toDartString($a0)));
  }).toJS;
}

void main() {
  final exports = JSObject();
  _install(exports);
  // Node CommonJS: node_preamble exposes `module.exports` as
  // `self.exports`; installing there makes the compiled file
  // a require()-able module.
  final moduleExports = globalContext['exports'];
  if (moduleExports != null && moduleExports.isA<JSObject>()) {
    _install(moduleExports as JSObject);
  }
  // WASM / browser fallback: a well-known global key.
  globalContext['__dtb_exports_boundary_logic__'] = exports;
}
