// Generated by dart_typescript_builder — do not edit.
// TypeScript declarations for the compiled Dart package
// `boundary_logic` (package:boundary_logic/boundary_logic.dart).
//
// Boundary semantics:
// - Dart `int`, `double` and `num` all cross as JS `number`
//   (IEEE-754 double); integers beyond 2^53 lose precision.
// - Dart `DateTime` crosses as JS `Date` via epoch
//   milliseconds: microseconds are truncated and the Dart
//   local/UTC flag is not preserved (arrives in Dart as UTC).
// - `unknown` marks Dart `dynamic`/`Object`: only
//   JSON-compatible values survive the boundary.
// - Class instances are opaque handles over Dart objects;
//   only handles created by this package can be passed back.

/**
 * Default page size used by [search].
 */
export const kDefaultLimit: number;

/**
 * Supported locales.
 */
export const kLocales: string[];

/**
 * Adds [days] days to [start].
 */
export function addDays(start: Date, days: number): Date;

/**
 * Echoes arbitrary JSON-ish data, adding a `seen: true` flag to maps.
 */
export function annotate(data: unknown): unknown;

/**
 * Returns a greeting after [delayMs] milliseconds.
 */
export function delayedGreet(name: string, delayMs: number): Promise<string>;

/**
 * Completes when the given promise resolves, doubling its value.
 */
export function doubleEventually(value: Promise<number>): Promise<number>;

/**
 * Counts characters per word.
 */
export function lengths(words: string[]): Record<string, number>;

/**
 * Length of [text], or null when [text] is null.
 */
export function maybeLength(text: string | null): number | null;

/**
 * Pads [text] to [width] using named options.
 */
export function pad(text: string, options: { width: number; fill?: string }): string;

/**
 * Repeats [text]; [times] is optional positional with a default.
 */
export function repeat(text: string, times?: number): string;

/**
 * Uppercases non-null entries, keeps nulls.
 */
export function shout(words: (string | null)[]): (string | null)[];

/**
 * Sums a list of integers.
 */
export function sum(values: number[]): number;

/**
 * A tagged note with creation time and free-form metadata.
 */
export interface Note {
  /**
   * Title of the note. Mutable from JS.
   */
  title: string;
  /**
   * Creation instant.
   */
  readonly createdAt: Date;
  /**
   * Free-form tags.
   */
  readonly tags: string[];
  /**
   * Arbitrary JSON-ish metadata.
   */
  meta: Record<string, unknown>;
  /**
   * Adds a tag and returns this note (for call chaining across the
   * boundary).
   */
  tag(value: string): Note;
  /**
   * Serializes to a JSON-ish map (includes a raw DateTime value).
   */
  toMap(): Record<string, unknown>;
}

/**
 * Creates a `Note` (Dart constructor `Note`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createNote(title: string, options: { createdAt: Date; tags?: string[] | null }): Note;

/**
 * Statics of the Dart class `Note` (static methods, named
 * constructors and factories, static constants).
 */
export const Note: {
  /**
   * A fresh template map (static getter — re-evaluated per access).
   */
  readonly template: Record<string, unknown>;
  /**
   * Rebuilds a note from [data] (`fromMap` static, tomorrowtech-style).
   */
  fromMap(data: Record<string, unknown>): Note;
  /**
   * Rebuilds many notes at once.
   */
  listFromMaps(data: Record<string, unknown>[]): Note[];
};

/**
 * An abstract contract with Stream members: exported as a TYPE-ONLY
 * TypeScript interface (AsyncIterable), never marshalled at runtime.
 */
export interface NoteRepository {
  getByTitle(title: string): Promise<Note | null>;
  watchAll(): AsyncIterable<Note[]>;
  save(options: { note: Note; overwrite: boolean }): Promise<void>;
}

/**
 * A notebook holding notes (class references in both directions).
 */
export interface Notebook {
  readonly name: string;
  readonly notes: Note[];
  /**
   * Adds a note (class-typed parameter).
   */
  add(note: Note): void;
  /**
   * Finds a note by title (nullable class-typed return).
   */
  find(title: string): Note | null;
  /**
   * All notes (list of class references).
   */
  all(): Note[];
  /**
   * Loads notes asynchronously (Future of class list).
   */
  load(): Promise<Note[]>;
}

/**
 * Creates a `Notebook` (Dart constructor `Notebook`).
 *
 * The returned value is an opaque handle to a Dart object,
 * not a plain JS object.
 */
export function createNotebook(name: string): Notebook;
